### ISSUE TITLE
Crash if vswitch/send_win is used from workspace with single window

### ISSUE THREAD

**Issue by not-chicken** [WayfireWM/wayfire#1233]
**Describe the bug**
If there is only one window on the workspace and vswitch plugin is used to send that window to other workspace using send_win_N or send_win_dir binding, then Wayfire crashes with a Segmentation Fault.

**To Reproduce**
1. Enable vswitch plugin and set bindings for send_win_N or send_win_dir
2. Use above bindings from a workspace with a single window.
3. Wayfire crashes.

**Expected behavior**
No crash.

**Screenshots or stacktrace**
```
#0  nonstd::observer_ptr<wf::view_interface_t>::operator bool (this=0x20)
    at ../src/api/wayfire/nonstd/observer_ptr.h:177
No locals.
#1  0x00007fffdc1c7f16 in wf::vswitch::control_bindings_t::get_target_view (
    this=0x117af60) at ../plugins/vswitch/wayfire/plugins/vswitch.hpp:433
        view = {ptr = 0x0}
#2  0x00007fffdc1d4afa in wf::vswitch::control_bindings_t::setup(std::function<bool (wf::point_t, nonstd::observer_ptr<wf::view_interface_t>, bool)>)::{lambda(wf::activatorbinding_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)#1}::operator()(wf::activatorbinding_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool) const::{lambda(wf::activator_data_t const&)#1}::operator()(wf::activator_data_t const&) const (
    this=0x11329c0) at ../plugins/vswitch/wayfire/plugins/vswitch.hpp:362
        target = {x = 1, y = 0}
        current = {x = 0, y = 0}
        view = {ptr = 0x133e3f8}
```

**Wayfire version**
master branch

**Comment by ammen99** [comment]
@not-chicken Thanks for the good bug report! I think the following should fix the issue, can you test it? http://ix.io/3sxR

**Comment by not-chicken** [comment]
Yes, it does fix this. :tada:
Thanks!
