### ISSUE TITLE
crash in wf::transfer_views when resuming from monitor powersave mode

### ISSUE THREAD

**Issue by lilydjwg** [WayfireWM/wayfire#1356]
**Describe the bug**

After some time the monitors (one laptop's and one external) enter powersave mode. When I come back and move my mouse, it powers on and shows expected screen for a fraction of second and goes back to lightdm.

I've seen the same stacktrace twice.

**To Reproduce**
1. Enable plugin perserve ouput
2. Leave until monitors enter powersave mode
3. Wake up monitors by moving mouse

It doesn't happen every time.

**Expected behavior**
No crash.

**Screenshots or stacktrace**
I've disabled `PRINT_TRACE` and got stacktrace from gdb instead. The line is at

```
156                 if ((view->get_output() == from) &&                                                                                                                                        
```

and the triggering instruction is `mov    0x28(%rax),%rax` while %rax is 0. The coredump file has been saved. If you want more info please give me instructions. I'm not good at digging C++ memory bugs.

```
#0  0x00005573b6fdef6e in wf::transfer_views(wf::output_t*, wf::output_t*) (from=0x5573b8f6e1b0, to=0x5573b898e700) at ../src/core/output-layout.cpp:156
#1  0x00005573b6fe002f in wf::output_layout_output_t::destroy_wayfire_output() (this=0x5573b8e4e600) at ../src/core/output-layout.cpp:528
#2  0x00005573b6fe2fe0 in wf::output_layout_output_t::apply_state(wf::output_state_t const&) (this=0x5573b8e4e600, state=...) at ../src/core/output-layout.cpp:832
#3  0x00005573b6fe3a50 in wf::output_layout_t::impl::apply_configuration(std::map<wlr_output*, wf::output_state_t, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, wf::output_state_t> > > const&) (this=0x5573b88deea0, config=std::map with 2 elements = {...}) at ../src/core/output-layout.cpp:1352
#4  0x00005573b6feeb7c in wf::output_layout_t::impl::remove_output(wlr_output*) (to_remove=<optimized out>, this=0x5573b88deea0) at ../src/core/output-layout.cpp:1091
#5  wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}::operator()(void*) const (__closure=<optimized out>) at ../src/core/output-layout.cpp:1077
#6  std::__invoke_impl<void, wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}&, void*>(std::__invoke_other, wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}&, void*&&) (__f=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:61
#7  std::__invoke_r<void, wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}&, void*>(wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}&, void*&&)
    (__fn=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:111
#8  std::_Function_handler<void (void*), wf::output_layout_t::impl::add_output(wlr_output*)::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&)
    (__functor=<optimized out>, __args#0=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:291
#9  0x00005573b6fd8fee in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:560
#10 wf::wl_listener_wrapper::emit(void*) (data=<optimized out>, this=<optimized out>) at ../src/wl-listener-wrapper.tpp:57
#11 wf::handle_wrapped_listener(wl_listener*, void*) (listener=<optimized out>, data=<optimized out>) at ../src/wl-listener-wrapper.tpp:10
#12 0x00007f4a053989ee in wlr_signal_emit_safe () at /usr/lib/libwlroots.so.10
#13 0x00007f4a053675c1 in wlr_output_destroy () at /usr/lib/libwlroots.so.10
#14 0x00007f4a05351e88 in  () at /usr/lib/libwlroots.so.10
#15 0x00007f4a053989ee in wlr_signal_emit_safe () at /usr/lib/libwlroots.so.10
#16 0x00007f4a0536319e in  () at /usr/lib/libwlroots.so.10
#17 0x00007f4a053ef04a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#18 0x00007f4a053ecbc7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#19 0x00005573b6fd7a48 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:350
```

Last lines of log:

```
II 19-11-21 14:32:17.120 - [backend/drm/drm.c:717] connector eDP-1: Modesetting with '1920x1080@60031mHz'
II 19-11-21 14:32:17.363 - [backend/drm/drm.c:717] connector DP-2: Modesetting with '3840x2160@59997mHz'
DD 19-11-21 14:32:18.638 - [src/core/core.cpp:596] focusing layer 0
DD 19-11-21 14:32:18.638 - [src/core/core.cpp:596] focusing layer 0
DD 19-11-21 14:32:18.652 - [src/core/core.cpp:596] focusing layer 0
DD 19-11-21 14:32:19.666 - [src/output/output.cpp:450] output DP-2: deactivate plugin cube
DD 19-11-21 14:32:19.667 - [src/core/seat/pointer.cpp:120] change cursor focus (null) -> 0x5573b8e46528
DD 19-11-21 14:32:19.682 - [src/output/output.cpp:450] output eDP-1: deactivate plugin cube
II 19-11-21 14:32:19.703 - [backend/drm/drm.c:1194] Scanning DRM connectors on /dev/dri/card0
II 19-11-21 14:32:19.708 - [backend/drm/drm.c:1393] 'DP-2' disconnected
II 19-11-21 14:32:19.709 - [src/core/output-layout.cpp:1086] remove output: DP-2
EE 19-11-21 14:32:19.709 - [src/core/output-layout.cpp:506] disabling output: DP-2
DD 19-11-21 14:32:19.711 - [plugins/single_plugins/preserve-output.cpp:148] Received pre-remove event: DP-2
DD 19-11-21 14:32:19.711 - [plugins/single_plugins/preserve-output.cpp:148] Received pre-remove event: DP-2
DD 19-11-21 14:32:19.711 - [plugins/single_plugins/preserve-output.cpp:138] Setting last focused output to: DP-2
DD 19-11-21 14:32:19.711 - [src/core/core.cpp:517] focus output: eDP-1
II 19-11-21 14:32:19.712 - [src/core/output-layout.cpp:140] transfer views from DP-2 -> eDP-1
(EE) failed to read Wayland events: Broken pipe
```

**Wayfire version**
git with my pull requests applied and `PRINT_TRACE` disabled.

**Comment by ammen99** [comment]
There have been many fixes in this direction, please open a new issue with a new backtrace if it still happens on Wayfire-git.
