### ISSUE TITLE
Moving tiled windows causes wayfire to crash

### ISSUE THREAD

**Issue by MrZammler** [WayfireWM/wayfire#1593]
**Describe the bug**

When there are 2 (or more) tiled windows, trying to move one using the mouse (using `button_move`) causes wayfire to crash.

**To Reproduce**
1. Enable plugin simple-tile
2. Open a window, put in tile mode.
3. Open another window put in tile mode as well.
4. Move one of the two to another's spot.
5. Crash

**Expected behavior**

Should not crash.

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

```
Oct 21 15:05:47 winterland wayfire[4316]: ../plugins/tile/tree-controller.cpp:247:21: runtime error: member access within null pointer of type 'struct preview_indication_view_t'
Oct 21 15:05:47 winterland wayfire[4316]: AddressSanitizer:DEADLYSIGNAL
Oct 21 15:05:47 winterland wayfire[4316]: =================================================================
Oct 21 15:05:47 winterland wayfire[4316]: ==4314==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f4038fd3f2a bp 0x7ffe6a89eb00 sp 0x7ffe6a89e9f0 T0)
Oct 21 15:05:47 winterland wayfire[4316]: ==4314==The signal is caused by a READ memory access.
Oct 21 15:05:47 winterland wayfire[4316]: ==4314==Hint: address points to the zero page.
Oct 21 15:05:47 winterland wayfire[4316]:     #0 0x7f4038fd3f2a in wf::tile::move_view_controller_t::ensure_preview(wf::point_t) ../plugins/tile/tree-controller.cpp:247
Oct 21 15:05:47 winterland wayfire[4316]:     #1 0x7f4038fd4dea in wf::tile::move_view_controller_t::input_motion(wf::point_t) ../plugins/tile/tree-controller.cpp:272
Oct 21 15:05:47 winterland wayfire[4316]:     #2 0x7f4038f23afe in auto wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}::operator()<int, int>(int, int) const (/home/evas/stuff/wayfire/install_wayfire/lib64/wayfire/libsimple-tile.so+0x243afe)
Oct 21 15:05:47 winterland wayfire[4316]:     #3 0x7f4038f8128e in void std::__invoke_impl<void, wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}&, int, int>(std::__invoke_other, wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}&, int&&, int&&) (/home/evas/stuff/wayfire/install_wayfire/lib64/wayfire/libsimple-tile.so+0x2a128e)
Oct 21 15:05:47 winterland wayfire[4316]:     #4 0x7f4038f78b80 in std::enable_if<is_invocable_r_v<void, wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}&, int, int>, void>::type std::__invoke_r<void, wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}&, int, int>(wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}&, int&&, int&&) (/home/evas/stuff/wayfire/install_wayfire/lib64/wayfire/libsimple-tile.so+0x298b80)
Oct 21 15:05:47 winterland wayfire[4316]:     #5 0x7f4038f6bc6e in std::_Function_handler<void (int, int), wf::tile_plugin_t::setup_callbacks()::{lambda(auto:1, auto:2)#2}>::_M_invoke(std::_Any_data const&, int&&, int&&) (/home/evas/stuff/wayfire/install_wayfire/lib64/wayfire/libsimple-tile.so+0x28bc6e)
Oct 21 15:05:47 winterland wayfire[4316]:     #6 0x5607087654c8 in std::function<void (int, int)>::operator()(int, int) const /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/std_function.h:590
Oct 21 15:05:47 winterland wayfire[4316]:     #7 0x56070875d597 in wf::pointer_t::send_motion(unsigned int) ../src/core/seat/pointer.cpp:269
Oct 21 15:05:47 winterland wayfire[4316]:     #8 0x5607087588a7 in wf::pointer_t::update_cursor_position(unsigned int, bool) ../src/core/seat/pointer.cpp:97
Oct 21 15:05:47 winterland wayfire[4316]:     #9 0x56070875e45a in wf::pointer_t::handle_pointer_motion(wlr_event_pointer_motion*, wf::input_event_processing_mode_t) ../src/core/seat/pointer.cpp:292
Oct 21 15:05:47 winterland wayfire[4316]:     #10 0x5607087703f9 in operator() ../src/core/seat/cursor.cpp:71
Oct 21 15:05:47 winterland wayfire[4316]:     #11 0x56070878e21a in __invoke_impl<void, wf::cursor_t::setup_listeners()::<lambda(void*)>&, void*> /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/invoke.h:61
Oct 21 15:05:47 winterland wayfire[4316]:     #12 0x560708789091 in __invoke_r<void, wf::cursor_t::setup_listeners()::<lambda(void*)>&, void*> /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/invoke.h:111
Oct 21 15:05:47 winterland wayfire[4316]:     #13 0x56070878541d in _M_invoke /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/std_function.h:290
Oct 21 15:05:47 winterland wayfire[4316]:     #14 0x56070842886d in std::function<void (void*)>::operator()(void*) const (/usr/bin/wayfire+0x11be86d)
Oct 21 15:05:47 winterland wayfire[4316]:     #15 0x560708426453 in wf::wl_listener_wrapper::emit(void*) ../src/wl-listener-wrapper.tpp:57
Oct 21 15:05:47 winterland wayfire[4316]:     #16 0x560708425e3a in handle_wrapped_listener ../src/wl-listener-wrapper.tpp:10
Oct 21 15:05:47 winterland wayfire[4316]:     #17 0x7f405a2d8deb in wlr_signal_emit_safe (/usr/lib64/libwlroots.so.10+0x84deb)
Oct 21 15:05:47 winterland wayfire[4316]:     #18 0x7f405a2d8deb in wlr_signal_emit_safe (/usr/lib64/libwlroots.so.10+0x84deb)
Oct 21 15:05:47 winterland wayfire[4316]:     #19 0x7f405a29a1d2  (/usr/lib64/libwlroots.so.10+0x461d2)
Oct 21 15:05:47 winterland wayfire[4316]:     #20 0x7f405a298f4a  (/usr/lib64/libwlroots.so.10+0x44f4a)
Oct 21 15:05:47 winterland wayfire[4316]:     #21 0x7f405a3329f1 in wl_event_loop_dispatch (/usr/lib64/libwayland-server.so.0+0xb9f1)
Oct 21 15:05:47 winterland wayfire[4316]:     #22 0x7f405a330414 in wl_display_run (/usr/lib64/libwayland-server.so.0+0x9414)
Oct 21 15:05:47 winterland wayfire[4316]:     #23 0x560708433d69 in main ../src/main.cpp:372
Oct 21 15:05:47 winterland wayfire[4316]:     #24 0x7f4059155349  (/lib64/libc.so.6+0x29349)
Oct 21 15:05:47 winterland wayfire[4316]:     #25 0x7f40591553fb in __libc_start_main (/lib64/libc.so.6+0x293fb)
Oct 21 15:05:47 winterland wayfire[4316]:     #26 0x560708425be0 in _start (/usr/bin/wayfire+0x11bbbe0)
Oct 21 15:05:47 winterland wayfire[4316]: 
Oct 21 15:05:47 winterland wayfire[4316]: AddressSanitizer can not provide additional info.
Oct 21 15:05:47 winterland wayfire[4316]: SUMMARY: AddressSanitizer: SEGV ../plugins/tile/tree-controller.cpp:247 in wf::tile::move_view_controller_t::ensure_preview(wf::point_t)
Oct 21 15:05:47 winterland wayfire[4316]: ==4314==ABORTING
Oct 21 15:05:47 winterland wayfire[4316]: (EE) failed to read Wayland events: Broken pipe
```

**Wayfire version**
0.5.0, git, package, something else?

Current master.

**Comment by ammen99** [comment]
Hi, I have recently noticed this problem as well, #1592 should fix this issue.

**Comment by MrZammler** [comment]
Indeed it does, thank you!
