### ISSUE TITLE
Segmentation fault when dragging window around or creating new windows

### ISSUE THREAD

**Issue by gustafla** [WayfireWM/wayfire#1954]
**Describe the bug**
I'm not sure what exactly causes this problem, but I have two monitors (1080p60 laptop screen and 1440p60 USB-C monitor), and dragging a terminal (footclient) around, resizing or creating new windows crash wayfire.

**To Reproduce**
1. Plugins I have enabled
```
plugins = \
  alpha \
  animate \
  autostart \
  command \
  cube \
  decoration \
  expo \
  fast-switcher \
  fisheye \
  foreign-toplevel \
  grid \
  gtk-shell \
  idle \
  invert \
  move \
  oswitch \
  place \
  resize \
  switcher \
  vswitch \
  wayfire-shell \
  window-rules \
  wm-actions \
  wobbly \
  wrot \
  zoom \
  follow-focus
```
2. Run footclient (put foot --server in autostart)
3. Drag the window around, resize it, move between monitors (idk what exactly)
4. Wayfire crashes

**Screenshots or stacktrace**
Remind me to get you a better stacktrace with sanitizer, this is just what gets logged into journalctl.
```
Oct 12 15:08:03 laurig-laptop wayfire[2546]: II 12-10-23 15:08:03.247 - [wayfire-0.8.0/src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: (null) app-id: footclient
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.579 - [wayfire-0.8.0/src/main.cpp:134] Fatal error: Segmentation fault
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.600 - #1  wf::print_trace(bool) ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.616 - #2  __sigaction ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.635 - #3  wf::view_bring_to_front(nonstd::observer_ptr<wf::view_interface_t>) ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.653 - #4  std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::view_fullscreen_request_signal>(wf::view_fullscreen_request_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.667 - #5  wl_event_loop_dispatch ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.680 - #6  wl_display_run ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.699 - #7  main ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.714 - #8  __libc_init_first ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.729 - #9  __libc_start_main ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2546]: EE 12-10-23 15:09:05.747 - #10 _start ??:?
Oct 12 15:09:05 laurig-laptop wayfire[2566]: (EE) failed to read Wayland events: Broken pipe
```

**Wayfire version**
0.8.0, from AUR (Arch Linux User Repository)
Runnin on Mesa 23.2.1, Radeon 680M GPU

**Comment by gustafla** [comment]
My guess is that follow-focus causes it. I can maybe investigate later.

**Comment by ammen99** [comment]
Looking at the stacktrace, I don't see anything which could cause the crash, so it would be great to have a better stacktrace (with address sanitizer). I just tried starting foot here, with and without follow-focus (also in a fullscreen mode), no crashes ..

**Comment by gustafla** [comment]
I'll see what I can do tomorrow with a different display but similar setup :)

**Comment by gustafla** [comment]
Here's a new one with asan. This is a different machine (a desktop PC with dual monitors)

```
Oct 13 18:18:25 lamer wayfire[44937]: II 13-10-23 18:18:25.900 - [wayfire-0.8.0/src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: (null) app-id: footclient
Oct 13 18:18:28 lamer wayfire[44937]: *** BUG ***
Oct 13 18:18:28 lamer wayfire[44937]: In pixman_region32_union_rect: Invalid rectangle passed
Oct 13 18:18:28 lamer wayfire[44937]: Set a breakpoint on '_pixman_log_error' to debug
Oct 13 18:18:28 lamer wayfire[44937]: *** BUG ***
Oct 13 18:18:28 lamer wayfire[44937]: In pixman_region32_union_rect: Invalid rectangle passed
Oct 13 18:18:28 lamer wayfire[44937]: Set a breakpoint on '_pixman_log_error' to debug
Oct 13 18:18:28 lamer wayfire[44937]: *** BUG ***
Oct 13 18:18:28 lamer wayfire[44937]: In pixman_region32_union_rect: Invalid rectangle passed
Oct 13 18:18:28 lamer wayfire[44937]: Set a breakpoint on '_pixman_log_error' to debug
Oct 13 18:18:30 lamer wayfire[44937]: AddressSanitizer:DEADLYSIGNAL
Oct 13 18:18:30 lamer wayfire[44937]: =================================================================
Oct 13 18:18:30 lamer wayfire[44937]: ==44937==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0x5636b02e3239 bp 0x7ffdfe98f620 sp 0x7ffdfe98ef20 T0)
Oct 13 18:18:30 lamer wayfire[44937]: ==44937==The signal is caused by a READ memory access.
Oct 13 18:18:30 lamer wayfire[44937]: ==44937==Hint: address points to the zero page.
Oct 13 18:18:30 lamer wayfire[44937]:     #0 0x5636b02e3239 in std::__uniq_ptr_impl<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::_M_ptr() const /usr/include/c++/13.2.1/bits/unique_ptr.h:199
Oct 13 18:18:30 lamer wayfire[44937]:     #1 0x5636b02e3239 in std::unique_ptr<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::get() const /usr/include/c++/13.2.1/bits/unique_ptr.h:470
Oct 13 18:18:30 lamer wayfire[44937]:     #2 0x5636b02e3239 in std::unique_ptr<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::operator->() const /usr/include/c++/13.2.1/bits/unique_ptr.h:463
Oct 13 18:18:30 lamer wayfire[44937]:     #3 0x5636b02e3239 in wf::view_interface_t::get_root_node() const ../wayfire-0.8.0/src/view/view.cpp:205
Oct 13 18:18:30 lamer wayfire[44937]:     #4 0x5636b02e3239 in wf::view_bring_to_front(nonstd::observer_ptr<wf::view_interface_t>) ../wayfire-0.8.0/src/view/view-impl.cpp:284
Oct 13 18:18:30 lamer wayfire[44937]:     #5 0x5636b013bed9 in std::function<void ()>::operator()() const /usr/include/c++/13.2.1/bits/std_function.h:591
Oct 13 18:18:30 lamer wayfire[44937]:     #6 0x5636b013bed9 in handle_timeout ../wayfire-0.8.0/src/util.cpp:32
Oct 13 18:18:30 lamer wayfire[44937]:     #7 0x7fa0d23d8d26 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbd26) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
Oct 13 18:18:30 lamer wayfire[44937]:     #8 0x7fa0d23d92d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
Oct 13 18:18:30 lamer wayfire[44937]:     #9 0x5636b01367b7 in main ../wayfire-0.8.0/src/main.cpp:417
Oct 13 18:18:30 lamer wayfire[44937]:     #10 0x7fa0d1358ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
Oct 13 18:18:30 lamer wayfire[44937]:     #11 0x7fa0d1358d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
Oct 13 18:18:30 lamer wayfire[44937]:     #12 0x5636b013b764 in _start (/usr/bin/wayfire+0xe9764) (BuildId: c271a467d4ce8feacffaf7c71ccdce16c97636e0)
Oct 13 18:18:30 lamer wayfire[44937]: AddressSanitizer can not provide additional info.
Oct 13 18:18:30 lamer wayfire[44937]: SUMMARY: AddressSanitizer: SEGV /usr/include/c++/13.2.1/bits/unique_ptr.h:199 in std::__uniq_ptr_impl<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::_M_ptr() const
Oct 13 18:18:30 lamer wayfire[44937]: ==44937==ABORTING
Oct 13 18:18:30 lamer wayfire[44957]: (EE) failed to read Wayland events: Broken pipe
```

**Comment by gustafla** [comment]
Also better steps to reproduce! Spam right click (and/or drag to resize) on the footclient window while holding the super key (resize modifier).

**Comment by ammen99** [comment]
Was this actually a debug or a release build? Because it feels like a few stackframes might be missing ... Also, were you able to confirm whether this is caused by follow-focus or not?

**Comment by ammen99** [comment]
> yes, oops, I left sway in some of the envvars

This might actually help a few things work ;) (xdg-desktop-portal-wlr)

**Comment by gustafla** [comment]
>Was this actually a debug or a release build? Because it feels like a few stackframes might be missing
Uhh it might be some weird build with -O2 but also -g -fsanitize=address... Let me change it to `-Og` in makepkg.conf and maybe the trace improves.

>Also, were you able to confirm whether this is caused by follow-focus or not?
I'll try that too, hang on.

**Comment by gustafla** [comment]
makepkg.conf:
```
#-- Compiler and Linker Flags
#CPPFLAGS=""
CFLAGS="-march=native -Og -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
#LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LDFLAGS="-Wl,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C opt-level=2 -C codegen-units=1 -Ctarget-cpu=native"
#-- Make Flags: change this for DistCC/SMP systems
MAKEFLAGS="-j$(nproc)"
#-- Debugging flags
DEBUG_CFLAGS="-g -fsanitize=address"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"
#DEBUG_RUSTFLAGS="-C debuginfo=2"
```

And also added to wayfire AUR package's PKGBUILD:
```
options=('!strip' 'debug') 
```

**Comment by ammen99** [comment]
Oh hey, I see the bug in follow-focus .. obviously it can be made to crash xD :) I'll open a PR soon.

**Comment by ammen99** [comment]
@gustafla Probably https://github.com/WayfireWM/wayfire-plugins-extra/pull/201 will fix the problem.

**Comment by gustafla** [comment]
Ah, great work! I'll test the patch soon. Just in case, heres my new build's trace

```
Oct 13 19:07:06 lamer wayfire[64288]: II 13-10-23 19:07:06.418 - [wayfire-0.8.0/src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: (null) app-id: footclient
Oct 13 19:07:07 lamer wayfire[64288]: AddressSanitizer:DEADLYSIGNAL
Oct 13 19:07:07 lamer wayfire[64288]: =================================================================
Oct 13 19:07:07 lamer wayfire[64288]: ==64288==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0x56417ce85c68 bp 0x6080002fe920 sp 0x7ffcdd15a7d8 T0)
Oct 13 19:07:07 lamer wayfire[64288]: ==64288==The signal is caused by a READ memory access.
Oct 13 19:07:07 lamer wayfire[64288]: ==64288==Hint: address points to the zero page.
Oct 13 19:07:07 lamer wayfire[64288]:     #0 0x56417ce85c68 in std::__uniq_ptr_impl<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::_M_ptr() const /usr/include/c++/13.2.1/bits/unique_ptr.h:199
Oct 13 19:07:07 lamer wayfire[64288]:     #1 0x56417ce85c68 in std::unique_ptr<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::get() const /usr/include/c++/13.2.1/bits/unique_ptr.h:470
Oct 13 19:07:07 lamer wayfire[64288]:     #2 0x56417ce85c68 in std::unique_ptr<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::operator->() const /usr/include/c++/13.2.1/bits/unique_ptr.h:463
Oct 13 19:07:07 lamer wayfire[64288]:     #3 0x56417ce85c68 in wf::view_interface_t::get_root_node() const ../wayfire-0.8.0/src/view/view.cpp:205
Oct 13 19:07:07 lamer wayfire[64288]:     #4 0x56417ceb3dda in wf::view_bring_to_front(nonstd::observer_ptr<wf::view_interface_t>) ../wayfire-0.8.0/src/view/view-impl.cpp:284
Oct 13 19:07:07 lamer wayfire[64288]:     #5 0x56417cd0ef3d in std::function<void ()>::operator()() const /usr/include/c++/13.2.1/bits/std_function.h:591
Oct 13 19:07:07 lamer wayfire[64288]:     #6 0x56417cd0f00e in wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}::operator()() const ../wayfire-0.8.0/src/util.cpp:128
Oct 13 19:07:07 lamer wayfire[64288]:     #7 0x56417cd0f036 in void std::__invoke_impl<void, wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}&>(std::__invoke_other, wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}&) /usr/include/c++/13.2.1/bits/invoke.h:61
Oct 13 19:07:07 lamer wayfire[64288]:     #8 0x56417cd0f036 in std::enable_if<is_invocable_r_v<void, wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}&>, void>::type std::__invoke_r<void, wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}&>(wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}&) /usr/include/c++/13.2.1/bits/invoke.h:111
Oct 13 19:07:07 lamer wayfire[64288]:     #9 0x56417cd0f036 in std::_Function_handler<void (), wf::wl_timer<false>::set_timeout(unsigned int, std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) /usr/include/c++/13.2.1/bits/std_function.h:290
Oct 13 19:07:07 lamer wayfire[64288]:     #10 0x56417cd0ef3d in std::function<void ()>::operator()() const /usr/include/c++/13.2.1/bits/std_function.h:591
Oct 13 19:07:07 lamer wayfire[64288]:     #11 0x56417cd0ef6d in handle_timeout ../wayfire-0.8.0/src/util.cpp:32
Oct 13 19:07:07 lamer wayfire[64288]:     #12 0x7fc7b1cc9d26 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbd26) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
Oct 13 19:07:07 lamer wayfire[64288]:     #13 0x7fc7b1cca2d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
Oct 13 19:07:07 lamer wayfire[64288]:     #14 0x56417cd19c8b in main ../wayfire-0.8.0/src/main.cpp:417
Oct 13 19:07:07 lamer wayfire[64288]:     #15 0x7fc7b0c45ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
Oct 13 19:07:07 lamer wayfire[64288]:     #16 0x7fc7b0c45d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
Oct 13 19:07:07 lamer wayfire[64288]:     #17 0x56417ccfe044 in _start (/usr/bin/wayfire+0xb2044) (BuildId: 2fc9e939c1ca43907bc1b9f186144aca1d34fe88)
Oct 13 19:07:07 lamer wayfire[64288]: AddressSanitizer can not provide additional info.
Oct 13 19:07:07 lamer wayfire[64288]: SUMMARY: AddressSanitizer: SEGV /usr/include/c++/13.2.1/bits/unique_ptr.h:199 in std::__uniq_ptr_impl<wf::view_interface_t::view_priv_impl, std::default_delete<wf::view_interface_t::view_priv_impl> >::_M_ptr() const
Oct 13 19:07:07 lamer wayfire[64288]: ==64288==ABORTING
Oct 13 19:07:07 lamer wayfire[64307]: (EE) failed to read Wayland events: Broken pipe
```

**Comment by gustafla** [comment]
I can no longer make it crash after patching wayfire-plugins-extra! :+1:
