### ISSUE TITLE
wtype Segmentation fault

### ISSUE THREAD

**Issue by AlexJakeGreen** [WayfireWM/wayfire#1961]
**Describe the bug**
Wayfire crashes when `wtype` is run

**To Reproduce**
[wayfire 0.8.0](https://github.com/WayfireWM/wayfire/releases/tag/v0.8.0)
[wtype 0.3](https://github.com/atx/wtype/releases/tag/v0.3)

1. Start Wayfire
2. Start terminal window
3. In terminal window run `wtype abc`

**Observed**
Wayfire crashed

**Expected behavior**
No crash

**Screenshots or stacktrace**
```
II 18-10-23 17:42:32.114 - [wayfire-0.8.0/src/core/seat/input-manager.cpp:47] handle new input: wlr_virtual_keyboard_v1, default mapping: wlr_virtual_keyboard_v1
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "Power Button" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "Video Bus" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "Video Bus" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "Lid Switch" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "Sleep Button" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "AT Translated Set 2 keyboard" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "ThinkPad Extra Buttons" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [types/wlr_cursor.c:875] Cannot map device "wlr_virtual_keyboard_v1" to output (not found in this cursor)
EE 18-10-23 17:42:32.120 - [wayfire-0.8.0/src/main.cpp:134] Fatal error: Segmentation fault
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
EE 18-10-23 17:42:32.139 - #1  _start ??:?
EE 18-10-23 17:42:32.148 - #2  __sigaction ??:?
EE 18-10-23 17:42:32.155 - #3  std::_Function_handler<bool (wf::activator_data_t const&), wayfire_wm_actions_output_t::on_toggle_above::{lambda(auto:1)#1}>::_M_invoke(std::_Any_data const&, wf::activator_data_t const&) ??:?
EE 18-10-23 17:42:32.164 - #4  void std::vector<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> >, std::allocator<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> > > >::_M_realloc_insert<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> > >(__gnu_cxx::__normal_iterator<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> >*, std::vector<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> >, std::allocator<std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> > > > >, std::unique_ptr<wf::text_input, std::default_delete<wf::text_input> >&&) ??:?
EE 18-10-23 17:42:32.173 - #5  wf::bindings_repository_t::handle_key(wf::keybinding_t const&, unsigned int) ??:?
EE 18-10-23 17:42:32.183 - #6  wf::keyboard_t::handle_keyboard_key(unsigned int, unsigned int) ??:?
EE 18-10-23 17:42:32.192 - #7  wf::keyboard_t::handle_keyboard_key(unsigned int, unsigned int) ??:?
EE 18-10-23 17:42:32.201 - #8  wf::wl_listener_wrapper::emit(void*) ??:?
EE 18-10-23 17:42:32.208 - #9  wl_signal_emit_mutable ??:?
EE 18-10-23 17:42:32.216 - #10 wlr_keyboard_notify_key ??:?
EE 18-10-23 17:42:32.223 - #11 wlr_viewporter_create ??:?
EE 18-10-23 17:42:32.230 - #12 ffi_prep_go_closure ??:?
EE 18-10-23 17:42:32.237 - #13 ffi_closure_free ??:?
EE 18-10-23 17:42:32.244 - #14 ffi_call ??:?
EE 18-10-23 17:42:32.251 - #15 wl_event_loop_get_destroy_listener ??:?
EE 18-10-23 17:42:32.257 - #16 wl_client_destroy ??:?
EE 18-10-23 17:42:32.264 - #17 wl_event_loop_dispatch ??:?
EE 18-10-23 17:42:32.271 - #18 wl_display_run ??:?
EE 18-10-23 17:42:32.280 - #19 main ??:?
EE 18-10-23 17:42:32.288 - #20 __libc_init_first ??:?
EE 18-10-23 17:42:32.296 - #21 __libc_start_main ??:?
EE 18-10-23 17:42:32.306 - #22 _start ??:?
The Wayland connection broke. Did the Wayland compositor die?
(EE) failed to read Wayland events: Broken pipe
A connection to the bus can't be made
```

**Wayfire version**
0.8.0 archive from the release page

**Comment by ammen99** [comment]
Weird, does Wayfire crash if you use the toggle above binding directly?

**Comment by ammen99** [comment]
Oh, this actually looks like the stack trace was not generated with address sanitizer .. so the last stack frame (which points to wm-actions) is probably a fluke.

**Comment by ammen99** [comment]
Wayfire seems to behave slightly weirdly here but I get no crash with wtype 0.3. It would be great if you could provide a stacktrace with address sanitizer to better see what is going on on your machine.

**Comment by AlexJakeGreen** [comment]
[wayfire.log.gz](https://github.com/WayfireWM/wayfire/files/13042393/wayfire.log.gz)
Full log ↑↑↑ and the interesting excerpt ↓↓↓:
```
II 19-10-23 13:42:29.376 - [wayfire-0.8.0/src/core/seat/input-manager.cpp:47] handle new input: wlr_virtual_keyboard_v1, default mapping: wlr_virtual_keyboard_v1
EE 19-10-23 13:42:29.388 - [types/wlr_cursor.c:875] Cannot map device "Power Button" to output (not found in this cursor)
EE 19-10-23 13:42:29.388 - [types/wlr_cursor.c:875] Cannot map device "Video Bus" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "Video Bus" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "Lid Switch" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "Sleep Button" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "AT Translated Set 2 keyboard" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "ThinkPad Extra Buttons" to output (not found in this cursor)
EE 19-10-23 13:42:29.389 - [types/wlr_cursor.c:875] Cannot map device "wlr_virtual_keyboard_v1" to output (not found in this cursor)
../wayfire-0.8.0/plugins/wm-actions/wm-actions.cpp:222:58: runtime error: member access within null pointer of type 'struct toplevel_view_interface_t'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==18725==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f0b9e7ab34b bp 0x7ffca38dfac0 sp 0x7ffca38df8a0 T0)
==18725==The signal is caused by a READ memory access.
==18725==Hint: address points to the zero page.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
    #0 0x7f0b9e7ab34b in bool wayfire_wm_actions_output_t::on_toggle_above::{lambda(auto:1)#1}::operator()<wf::activator_data_t>(wayfire_wm_actions_output_t::on_toggle_above) const (/usr/lib64/wayfire/libwm-actions.so+0x27f34b)
    #1 0x55baf9fc5073  (/usr/bin/wayfire+0x219f073)
    #2 0x55baf9ff0472 in wf::bindings_repository_t::handle_key(wf::keybinding_t const&, unsigned int) (/usr/bin/wayfire+0x21ca472)
    #3 0x55bafa06d430 in wf::keyboard_t::handle_keyboard_key(unsigned int, unsigned int) (/usr/bin/wayfire+0x2247430)
    #4 0x55bafa06f343  (/usr/bin/wayfire+0x2249343)
    #5 0x55baf9bf8a6b in wf::wl_listener_wrapper::emit(void*) (/usr/bin/wayfire+0x1dd2a6b)
    #6 0x7f0bcb4b9a0b in wl_signal_emit_mutable (/usr/lib64/libwayland-server.so.0+0x9a0b)
    #7 0x7f0bcb428def in wlr_keyboard_notify_key (/usr/lib64/libwlroots.so.11+0x7bdef)
    #8 0x7f0bcb43844d  (/usr/lib64/libwlroots.so.11+0x8b44d)
    #9 0x7f0bca56cfc9  (/usr/lib64/libffi.so.8+0x6fc9)
    #10 0x7f0bca56c47b  (/usr/lib64/libffi.so.8+0x647b)
    #11 0x7f0bca56cb5c in ffi_call (/usr/lib64/libffi.so.8+0x6b5c)
    #12 0x7f0bcb4bd7f5  (/usr/lib64/libwayland-server.so.0+0xd7f5)
    #13 0x7f0bcb4b8c85  (/usr/lib64/libwayland-server.so.0+0x8c85)
    #14 0x7f0bcb4bb941 in wl_event_loop_dispatch (/usr/lib64/libwayland-server.so.0+0xb941)
    #15 0x7f0bcb4b9454 in wl_display_run (/usr/lib64/libwayland-server.so.0+0x9454)
    #16 0x55baf9ba916a in main (/usr/bin/wayfire+0x1d8316a)
    #17 0x7f0bca5979c9  (/lib64/libc.so.6+0x239c9)
    #18 0x7f0bca597a84 in __libc_start_main (/lib64/libc.so.6+0x23a84)
    #19 0x55baf9baeab0 in _start (/usr/bin/wayfire+0x1d88ab0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/wayfire/libwm-actions.so+0x27f34b) in bool wayfire_wm_actions_output_t::on_toggle_above::{lambda(auto:1)#1}::operator()<wf::activator_data_t>(wayfire_wm_actions_output_t::on_toggle_above) const
==18725==ABORTING
A connection to the bus can't be made
```

**Comment by ammen99** [comment]
Huh so the problem is indeed in wm-actions .. Does it happen if you trigger it manually from a 'real' keyboard?

**Comment by ammen99** [comment]
Looking at this again, a similar issue was brought to my attention on matrix. Likely wtype is using a non-standard keymap, which means that maybe that when typing 'A' it sends a weird (from Wayfire's perspecitve) keycode which happens to match the binding for wm-actions - I suppose the crash will go away if you disable the wm-actions plugin. I plan to fix this for the next release (the solution would be to provide bindings which map to xkb keysyms instead of evdev keycodes like we currently have). In the meantime, I would suggest using newer wtype, since you said it works ;)

**Comment by ammen99** [comment]
#1989 fixes the crash, the actual bug will probably be fixable when #1601 is resolved.
