### ISSUE TITLE
Segmentation fault when toggling on Blur plugin at runtime with WCM

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#2012]
**Describe the bug**
I turned on the Blur plugin at runtime after having the desktop running for at least 24 hours. I have produced backtraces.

**To Reproduce**
1. Start Wayfire with blur disabled
2. Start WCM
3. Enable Blur by clicking the checkbox.

**Expected behavior**
Blur should start functioning without crashing.

**Screenshots or stacktrace**
Backtrace from the original crash:
```
#0  wlr_addon_find
    (set=0x330, owner=0x0, impl=0x7f17291a9fb0 <surface_addon_impl>)
    at ../subprojects/wlroots/util/addon.c:49
#1  0x00007f172913e07e in wlr_xwayland_surface_try_from_wlr_surface
    (surface=<optimized out>) at ../subprojects/wlroots/xwayland/xwm.c:117
#2  0x000055b138027888 in wf::view_access_interface_t::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&)
    (this=0x7ffd61d48930, identifier="type", error=<optimized out>)
    at ../src/core/view-access-interface.cpp:114
#3  0x00007f17290347ad in wf::equals_condition_t::evaluate(wf::access_interface_t&, bool&)
    (error=@0x7ffd61d4892f: false, interface=<optimized out>, this=0x55b139aab150) at ../subprojects/wf-utils/wayfire/condition/test_condition.cpp:71
#4  wf::equals_condition_t::evaluate(wf::access_interface_t&, bool&)
    (this=0x55b139aab150, interface=<optimized out>, error=@0x7ffd61d4892f: false) at ../subprojects/wf-utils/wayfire/condition/test_condition.cpp:64
#5  0x000055b13800d89d in wf::view_matcher_t::matches(nonstd::observer_ptr<wf::view_interface_t>) (this=this@entry=0x55b139fe7f58, view=...)
    at ../src/core/matcher.cpp:118
#6  0x00007f170040c265 in wayfire_blur::init() (this=0x55b139fe7e50)
    at ../plugins/blur/blur.cpp:339
#7  0x000055b13800f9db in wf::plugin_manager_t::reload_dynamic_plugins()
    (this=<optimized out>) at ../src/core/plugin-loader.cpp:222
#8  0x00007f172901fa23 in wl_event_loop_dispatch_idle
    (loop=loop@entry=0x55b138866ea0) at ../wayland-1.22.0/src/event-loop.c:969
#9  0x00007f172901fb3d in wl_event_loop_dispatch
    (loop=0x55b138866ea0, timeout=timeout@entry=-1)
    at ../wayland-1.22.0/src/event-loop.c:1032
#10 0x00007f17290202d7 in wl_display_run (display=0x55b138866db0)
    at ../wayland-1.22.0/src/wayland-server.c:1493
#11 0x000055b137ff1136 in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:418
```

Backtrace upon attempting to start a new session without rebooting:
```
#0  wlr_backend_get_drm_fd (backend=0x0)
    at ../subprojects/wlroots/backend/backend.c:120
120             if (!backend->impl->get_drm_fd) {
(gdb) bt
#0  wlr_backend_get_drm_fd (backend=0x0)
    at ../subprojects/wlroots/backend/backend.c:120
#1  0x00005652f5d6a9fb in main(int, char**) (argc=1, argv=0x7ffd2b047928)
    at ../src/main.cpp:348
```

**Wayfire version**
track-wlroots 94ac0bf6

**Comment by kode54** [comment]
Maybe I shouldn't report bugs in this branch to the tracker. This was a bug in the track-wlroots branch, removing a NULL check that the new function still requires. Closing.
