### ISSUE TITLE
Mouse confinement will cause Wayfire to crash after turning off/on the monitor.

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2223]
Just start any game that hold mouse cursor, turn off/on the monitor(s)

<details>

```
EE 16-03-24 16:41:37.196 - #1  wf::print_trace(bool) ../src/debug.cpp:227
EE 16-03-24 16:41:37.476 - #2  wf::scene::node_t::set_children_unchecked(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ??:?
EE 16-03-24 16:41:37.755 - #3  wf::scene::floating_inner_node_t::set_children_list(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ??:?
EE 16-03-24 16:41:38.039 - #4  wf::scene::add_front(std::shared_ptr<wf::scene::floating_inner_node_t>, std::shared_ptr<wf::scene::node_t>) :?
EE 16-03-24 16:41:38.318 - #5  wf::move_view_to_output(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool) ??:?
EE 16-03-24 16:41:38.601 - #6  wf::window_manager_t::fullscreen_request(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool, std::optional<wf::point_t>) ??:?
EE 16-03-24 16:41:38.880 - #7  std::_Function_handler<void (void*), wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}>::_M_invoke(std::_Any_data const&, void*&&) ??:?
EE 16-03-24 16:41:38.939 - #8  wf::handle_wrapped_listener(wl_listener*, void*) ../src/wl-listener-wrapper.tpp:7
EE 16-03-24 16:41:38.949 - #9  wl_signal_emit_mutable ??:?
EE 16-03-24 16:41:38.986 - #10 x11_event_handler :?
EE 16-03-24 16:41:38.996 - #11 wl_event_loop_dispatch ??:?
EE 16-03-24 16:41:39.006 - #12 wl_display_run ??:?
EE 16-03-24 16:41:39.063 - #13 main ../src/main.cpp:444
EE 16-03-24 16:41:39.076 - #14 __libc_init_first ??:?
EE 16-03-24 16:41:39.087 - #15 __libc_start_main ??:?
EE 16-03-24 16:41:39.379 - #16 _start ??:?
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1006==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x5a804ba899c7 bp 0x7ffedff8e2b0 sp 0x7ffedff8e200 T0)
==1006==The signal is caused by a READ memory access.
==1006==Hint: address points to the zero page.
    #0 0x5a804ba899c7 in std::__uniq_ptr_impl<wf::output_layout_t::impl, std::default_delete<wf::output_layout_t::impl> >::_M_ptr() const /usr/include/c++/13.2.1/bits/unique_ptr.h:199
    #1 0x5a804ba899c7 in std::unique_ptr<wf::output_layout_t::impl, std::default_delete<wf::output_layout_t::impl> >::get() const /usr/include/c++/13.2.1/bits/unique_ptr.h:470
    #2 0x5a804ba899c7 in std::unique_ptr<wf::output_layout_t::impl, std::default_delete<wf::output_layout_t::impl> >::operator->() const /usr/include/c++/13.2.1/bits/unique_ptr.h:463
    #3 0x5a804ba899c7 in wf::output_layout_t::get_handle() ../src/core/output-layout.cpp:1723
    #4 0x5a804ba899c7 in wf::output_t::get_layout_geometry() const ../src/output/output.cpp:181
    #5 0x5a804b8b3404 in wf::scene::output_node_t::get_bounding_box() ../src/core/scene.cpp:442
    #6 0x5a804b8b95f8 in wf::scene::node_t::set_children_unchecked(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:130
    #7 0x5a804b8ba5b0 in wf::scene::floating_inner_node_t::set_children_list(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:123
    #8 0x5a804baa1a0d in wf::output_impl_t::~output_impl_t() ../src/output/output.cpp:154
    #9 0x5a804b842ac7 in wf::output_impl_t::~output_impl_t() ../src/output/output.cpp:157
    #10 0x5a804b842ac7 in std::default_delete<wf::output_impl_t>::operator()(wf::output_impl_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #11 0x5a804b842ac7 in std::unique_ptr<wf::output_impl_t, std::default_delete<wf::output_impl_t> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #12 0x5a804b842ac7 in wf::output_layout_output_t::~output_layout_output_t() ../src/core/output-layout.cpp:236
    #13 0x5a804b842ac7 in std::default_delete<wf::output_layout_output_t>::operator()(wf::output_layout_output_t*) const [clone .part.0] [clone .lto_priv.0] /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #14 0x5a804b84913a in std::default_delete<wf::output_layout_output_t>::operator()(wf::output_layout_output_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:93
    #15 0x5a804b84913a in std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #16 0x5a804b84913a in std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >::~pair() /usr/include/c++/13.2.1/bits/stl_pair.h:187
    #17 0x5a804b84913a in void std::__new_allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::destroy<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >(std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >*) /usr/include/c++/13.2.1/bits/new_allocator.h:194
    #18 0x5a804b84913a in void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > > >::destroy<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >(std::allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >&, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >*) /usr/include/c++/13.2.1/bits/alloc_traits.h:557
    #19 0x5a804b84913a in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_destroy_node(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:625
    #20 0x5a804b84913a in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_drop_node(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:633
    #21 0x5a804b84913a in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_erase(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:1938
    #22 0x5a804b84913a in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::~_Rb_tree() /usr/include/c++/13.2.1/bits/stl_tree.h:986
    #23 0x5a804b84913a in std::map<wlr_output*, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::~map() /usr/include/c++/13.2.1/bits/stl_map.h:314
    #24 0x5a804b84913a in wf::output_layout_t::impl::~impl() ../src/core/output-layout.cpp:904
    #25 0x5a804b84913a in std::default_delete<wf::output_layout_t::impl>::operator()(wf::output_layout_t::impl*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #26 0x5a804b84913a in std::default_delete<wf::output_layout_t::impl>::operator()(wf::output_layout_t::impl*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:93
    #27 0x5a804b84913a in std::unique_ptr<wf::output_layout_t::impl, std::default_delete<wf::output_layout_t::impl> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #28 0x5a804b84913a in wf::output_layout_t::~output_layout_t() ../src/core/output-layout.cpp:1719
    #29 0x5a804b8c89d0 in std::default_delete<wf::output_layout_t>::operator()(wf::output_layout_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #30 0x5a804b8c89d0 in std::default_delete<wf::output_layout_t>::operator()(wf::output_layout_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:93
    #31 0x5a804b8c89d0 in std::__uniq_ptr_impl<wf::output_layout_t, std::default_delete<wf::output_layout_t> >::reset(wf::output_layout_t*) /usr/include/c++/13.2.1/bits/unique_ptr.h:211
    #32 0x5a804b8c89d0 in std::unique_ptr<wf::output_layout_t, std::default_delete<wf::output_layout_t> >::reset(wf::output_layout_t*) /usr/include/c++/13.2.1/bits/unique_ptr.h:509
    #33 0x5a804b8c89d0 in wf::compositor_core_impl_t::~compositor_core_impl_t() ../src/core/core.cpp:555
    #34 0x5a804b8d0503 in wf::compositor_core_impl_t::~compositor_core_impl_t() ../src/core/core.cpp:556
    #35 0x5a804b8d0503 in std::default_delete<wf::compositor_core_impl_t>::operator()(wf::compositor_core_impl_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #36 0x5a804b8d0503 in std::unique_ptr<wf::compositor_core_impl_t, std::default_delete<wf::compositor_core_impl_t> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #37 0x7e616925cb35  (/usr/lib/libc.so.6+0x3eb35) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #38 0x7e616925cc7f in exit (/usr/lib/libc.so.6+0x3ec7f) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #39 0x5a804b8ba287 in wf::dassert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../src/api/wayfire/dassert.hpp:28
    #40 0x5a804b8ba287 in wf::scene::node_t::set_children_unchecked(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:139
    #41 0x5a804b8ba5b0 in wf::scene::floating_inner_node_t::set_children_list(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:123
    #42 0x5a804b8bab2f in wf::scene::add_front(std::shared_ptr<wf::scene::floating_inner_node_t>, std::shared_ptr<wf::scene::node_t>) ../src/api/wayfire/scene-operations.hpp:38
    #43 0x5a804b8bb6e3 in wf::move_view_to_output(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool) ../src/core/core.cpp:514
    #44 0x5a804b81af1b in wf::window_manager_t::fullscreen_request(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool, std::optional<wf::point_t>) ../src/core/window-manager.cpp:256
    #45 0x5a804ba17b88 in wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}::operator()(void*) const ../src/view/xwayland/xwayland-toplevel-view.hpp:206
    #46 0x5a804ba17b88 in void std::__invoke_impl<void, wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}&, void*>(std::__invoke_other, wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}&, void*&&) /usr/include/c++/13.2.1/bits/invoke.h:61
    #47 0x5a804ba17b88 in std::enable_if<is_invocable_r_v<void, wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}&, void*>, void>::type std::__invoke_r<void, wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}&, void*>(wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}&, void*&&) /usr/include/c++/13.2.1/bits/invoke.h:111
    #48 0x5a804ba17b88 in std::_Function_handler<void (void*), wayfire_xwayland_view::wayfire_xwayland_view(wlr_xwayland_surface*)::{lambda(void*)#4}>::_M_invoke(std::_Any_data const&, void*&&) /usr/include/c++/13.2.1/bits/std_function.h:290
    #49 0x5a804b7f4309 in std::function<void (void*)>::operator()(void*) const /usr/include/c++/13.2.1/bits/std_function.h:591
    #50 0x5a804b7f4309 in wf::wl_listener_wrapper::emit(void*) ../src/wl-listener-wrapper.tpp:57
    #51 0x5a804b7f4309 in handle_wrapped_listener ../src/wl-listener-wrapper.tpp:10
    #52 0x7e616a13701d in wl_signal_emit_mutable (/usr/lib/libwayland-server.so.0+0xa01d) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #53 0x7e616a212354 in xwm_handle_net_wm_state_message ../subprojects/wlroots/xwayland/xwm.c:1353
    #54 0x7e616a212354 in xwm_handle_client_message ../subprojects/wlroots/xwayland/xwm.c:1514
    #55 0x7e616a212354 in x11_event_handler ../subprojects/wlroots/xwayland/xwm.c:1685
    #56 0x7e616a212354 in x11_event_handler ../subprojects/wlroots/xwayland/xwm.c:1632
    #57 0x7e616a138b8e in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbb8e) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #58 0x7e616a1392d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #59 0x5a804b7ef18e in main ../src/main.cpp:443
    #60 0x7e6169243ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #61 0x7e6169243d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #62 0x5a804b7f4064 in _start (/usr/bin/wayfire+0xf9064) (BuildId: d009ff5c9efbc464b68878e5cb11a38b4f0fc053)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/13.2.1/bits/unique_ptr.h:199 in std::__uniq_ptr_impl<wf::output_layout_t::impl, std::default_delete<wf::output_layout_t::impl> >::_M_ptr() const
==1006==ABORTING
(EE) failed to read Wayland events: Connection reset by peer
```

**Comment by killown** [comment]
you randomly fixed this issue at some point, not happening anymore

**Comment by ammen99** [comment]
Alright :)
