### ISSUE TITLE
Wayfire hangs if using keyboard shortcut to launch after switching workspaces

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#224]
After switching workspace with `Ctrl+Alt+Left Arrow` and using `Super+d` to launch any application, wayfire stops responding.

Steps to reproduce:
1) Start wayfire
2) Switch workspaces (at least need to switch once and can also go back to original workspace)
3) Press `Super+d` (by default bound to `dmenu`, I have bound it to `kitty`)

Expected result:  Start `kitty`

Error: Wayfire stops responding

Debug log with asan and debug symbols from ninja:
```
#0  0x00007ffa4fa6beca in waitpid () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffa50de7e4c in __interceptor_waitpid (pid=<optimized out>, status=0x7ffe00374c30, options=<optimized out>)
    at /var/tmp/portage/sys-devel/gcc-8.3.0-r1/work/gcc-8.3.0/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:2204
        ctx = <optimized out>
        _ctx = <optimized out>
        res = <optimized out>
        v1 = <optimized out>
        v2 = <optimized out>
#2  0x000055891a46a45d in wayfire_core::run (this=0x619000000580, command=0x7ffe00375020 "kitty") at ../src/core/core.cpp:423
        status = -1073288808
        pid = 1097
#3  0x00007ffa3f06e2da in wayfire_command::on_binding (this=0x61200012a9c0, command="kitty", enable_repeat=false, source=ACTIVATOR_SOURCE_KEYBINDING, value=32)
    at ../plugins/single_plugins/command.cpp:61
No locals.
#4  0x00007ffa3f0814bf in std::__invoke_impl<void, void (wayfire_command::* const&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int), wayfire_command*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, wf_activator_source, unsigned int> (__f=
    @0x606000039c20: (void (wayfire_command::*)(wayfire_command * const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)) 0x7ffa3f06e04c <wayfire_command::on_binding(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)>, __t=@0x606000039c58: 0x61200012a9c0, __args#0="kitty", __args#1=@0x606000039c30: false, __args#2=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, 
    __args#3=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/invoke.h:73
No locals.
#5  0x00007ffa3f080aaa in std::__invoke<void (wayfire_command::* const&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int), wayfire_command*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, wf_activator_source, unsigned int> (
    __fn=
    @0x606000039c20: (void (wayfire_command::*)(wayfire_command * const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)) 0x7ffa3f06e04c <wayfire_command::on_binding(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)>, __args#0=@0x606000039c58: 0x61200012a9c0, __args#1="kitty", __args#2=@0x606000039c30: false, __args#3=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, 
    __args#4=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/invoke.h:95
No locals.
#6  0x00007ffa3f08037e in std::_Mem_fn_base<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int), true>::operator()<wayfire_command*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, wf_activator_source, unsigned int> (this=0x606000039c20, __args#0=@0x606000039c58: 0x61200012a9c0, __args#1="kitty", __args#2=@0x606000039c30: false, 
    __args#3=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, __args#4=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/functional:114
No locals.
#7  0x00007ffa3f07fc26 in std::__invoke_impl<void, std::_Mem_fn<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)>&, wayfire_command*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, wf_activator_source, unsigned int> (__f=..., __args#0=@0x606000039c58: 0x61200012a9c0, __args#1="kitty", __args#2=@0x606000039c30: false, 
    __args#3=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, __args#4=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/invoke.h:60
No locals.
#8  0x00007ffa3f07f21b in std::__invoke<std::_Mem_fn<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)>&, wayfire_command*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, wf_activator_source, unsigned int> (__fn=..., __args#0=@0x606000039c58: 0x61200012a9c0, __args#1="kitty", __args#2=@0x606000039c30: false, __args#3=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, 
    __args#4=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/invoke.h:95
No locals.
#9  0x00007ffa3f07e3b4 in std::_Bind<std::_Mem_fn<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)> (wayfire_command*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::_Placeholder<1>, std::_Placeholder<2>)>::__call<void, wf_activator_source&&, unsigned int&&, 0ul, 1ul, 2ul, 3ul, 4ul>(std::tuple<wf_activator_source&&, unsigned int&&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (this=0x606000039c20, __args=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/functional:400
No locals.
#10 0x00007ffa3f07c6d4 in std::_Bind<std::_Mem_fn<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)> (wayfire_command*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::_Placeholder<1>, std::_Placeholder<2>)>::operator()<wf_activator_source, unsigned int, void>(wf_activator_source&&, unsigned int&&) (this=0x606000039c20, 
    __args#0=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, __args#1=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/functional:484
No locals.
#11 0x00007ffa3f079948 in std::_Function_handler<void (wf_activator_source, unsigned int), std::_Bind<std::_Mem_fn<void (wayfire_command::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, wf_activator_source, unsigned int)> (wayfire_command*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, wf_activator_source&&, unsigned int&&) (__functor=..., 
    __args#0=@0x7ffe003756b0: ACTIVATOR_SOURCE_KEYBINDING, __args#1=@0x7ffe003756f0: 32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:297
No locals.
#12 0x000055891a4baf2e in std::function<void (wf_activator_source, unsigned int)>::operator()(wf_activator_source, unsigned int) const (this=0x611000067ec0, 
    __args#0=ACTIVATOR_SOURCE_KEYBINDING, __args#1=32) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:687
No locals.
#13 0x000055891a4b67b2 in input_manager::<lambda()>::operator()(void) const (__closure=0x60300028a2c0) at ../src/core/seat/keyboard.cpp:202
        callback = 0x611000067ec0
        this = 0x617000020300
        actual_key = 32
#14 0x000055891a4b9a7e in std::_Function_handler<void(), input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:297
No locals.
#15 0x000055891a41a368 in std::function<void ()>::operator()() const (this=0x7ffe00375ca0) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:687
No locals.
#16 0x000055891a4b8404 in input_manager::handle_keyboard_key (this=0x617000020300, key=32, state=1) at ../src/core/seat/keyboard.cpp:269
        call = {<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, 
            _M_functor = {_M_unused = {_M_object = 0x60300028a2c0, _M_const_object = 0x60300028a2c0, _M_function_pointer = 0x60300028a2c0, 
                _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x60300028a2c0, this adjustment 140713026939720}, 
              _M_pod_data = "��(\000\060`\000\000Hk�M�\177\000"}, 
            _M_manager = 0x55891a4b9a81 <std::_Function_base::_Base_manager<input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, 
          _M_invoker = 0x55891a4b9a5e <std::_Function_handler<void(), input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &)>}
        __for_range = std::vector of length 1, capacity 1 = {{<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {
              static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x60300028a260, _M_const_object = 0x60300028a260, 
                  _M_function_pointer = 0x60300028a260, 
                  _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x60300028a260, this adjustment 140728902048544}, 
                _M_pod_data = "`�(\000\060`\000\000 [7\000�\177\000"}, 
              _M_manager = 0x55891a4b9a81 <std::_Function_base::_Base_manager<input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, 
            _M_invoker = 0x55891a4b9a5e <std::_Function_handler<void(), input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &)>}}
        __for_begin = 
  {<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x60300028a260, _M_const_object = 0x60300028a260, _M_function_pointer = 0x60300028a260, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x60300028a260, this adjustment 140728902048544}, _M_pod_data = "`�(\000\060`\000\000 [7\000�\177\000"}, _M_manager = 0x55891a4b9a81 <std::_Function_base::_Base_manager<input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, _M_invoker = 0x55891a4b9a5e <std::_Function_handler<void(), input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &)>}
        __for_end = 
  {<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x4ffffff00000002, _M_const_object = 0x4ffffff00000002, _M_function_pointer = 0x4ffffff00000002, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x4ffffff00000002, this adjustment 4863888070006538264}, _M_pod_data = "\002\000\000\000���\004\030\000\000\000n\000\200C"}, _M_manager = 0x611000067ec0}, _M_invoker = 0x617000020300}
        mod = 0
        callbacks = std::vector of length 1, capacity 1 = {{<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {
              static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x60300028a260, _M_const_object = 0x60300028a260, 
                  _M_function_pointer = 0x60300028a260, 
                  _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x60300028a260, this adjustment 140728902048544}, 
                _M_pod_data = "`�(\000\060`\000\000 [7\000�\177\000"}, 
              _M_manager = 0x55891a4b9a81 <std::_Function_base::_Base_manager<input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>}, 
            _M_invoker = 0x55891a4b9a5e <std::_Function_handler<void(), input_manager::match_keys(uint32_t, uint32_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &)>}}
        kbd = 0x6130000a7780
        iv = 0x0
#17 0x000055891a4b3817 in wf_keyboard::<lambda(void*)>::operator()(void *) const (__closure=0x611000093840, data=0x7ffe00375fc0) at ../src/core/seat/keyboard.cpp:28
        ev = 0x7ffe00375fc0
        seat = 0x61800002d080
        this = 0x611000093840
#18 0x000055891a4b9176 in std::_Function_handler<void(void*), wf_keyboard::setup_listeners()::<lambda(void*)> >::_M_invoke(const std::_Any_data &, void *&&) (
    __functor=..., __args#0=@0x7ffe00375dd0: 0x7ffe00375fc0) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:297
No locals.
#19 0x000055891a42b804 in std::function<void (void*)>::operator()(void*) const (this=0x611000093840, __args#0=0x7ffe00375fc0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:687
No locals.
#20 0x000055891a42a9bf in wf::wl_listener_wrapper::emit (this=0x611000093840, data=0x7ffe00375fc0) at ../src/util.cpp:386
No locals.
#21 0x000055891a42a5a4 in handle_wrapped_listener (listener=<error reading variable: Cannot access memory at address 0xfffffffffffffdc0>, data=0x7ffe00375fc0)
    at ../src/util.cpp:328
        wrap = 0x611000093860
#22 0x00007ffa50b2fdac in ?? () from /usr/lib64/libwlroots.so.3
No symbol table info available.
#23 0x00007ffa50b1eb64 in wlr_keyboard_notify_key () from /usr/lib64/libwlroots.so.3
No symbol table info available.
#24 0x00007ffa50af9b11 in ?? () from /usr/lib64/libwlroots.so.3
No symbol table info available.
#25 0x00007ffa50af89db in ?? () from /usr/lib64/libwlroots.so.3
No symbol table info available.
#26 0x00007ffa50b70152 in wl_event_loop_dispatch () from /usr/lib64/libwayland-server.so.0
No symbol table info available.
#27 0x00007ffa50b6ed02 in wl_display_run () from /usr/lib64/libwayland-server.so.0
No symbol table info available.
#28 0x000055891a417a25 in main (argc=1, argv=0x7ffe00376658) at ../src/main.cpp:228
        config_dir = "/home/epsilon/.config/"
        opts = {{name = 0x55891a5cb7c0 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55891a5cb800 "damage-debug", has_arg = 0, flag = 0x0, val = 100}, {
            name = 0x55891a5cb840 "damage-rerender", has_arg = 0, flag = 0x0, val = 82}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        c = -1
        i = 3630032
        display = 0x611000000040
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        inotify_fd = 13
        server_name = 0x612000126959 "wayland-0"
Detaching from program: /usr/bin/wayfire, process 964
```

**Comment by ammen99** [comment]
This is very strange. Which distro are you using?

**Comment by epsilon-0** [comment]
(I am epsilonknot on irc)
I am using gentoo with the latest wlroots and wayfire only.

**Comment by soreau** [comment]
Alternatively, does [this patch](http://ix.io/1JHt) work for you?

**Comment by epsilon-0** [comment]
yes that also works.

**Comment by soreau** [comment]
Great, thanks for testing.
