### ISSUE TITLE
wobbly state will crash wayfire

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2289]
also reproducible with new waypy test_wayfire()
<details>

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==25004==ERROR: AddressSanitizer: FPE on unknown address 0x72b3d08ded0c (pc 0x72b3d08ded0c bp 0x7ffe71925810 sp 0x7ffe719257f0 T0)
    #0 0x72b3d08ded0c in wobbly_resize ../plugins/wobbly/wobbly.c:606
    #1 0x72b3d08df155 in wf::wobbly_state_grabbed_t::handle_frame() ../plugins/wobbly/wobbly.cpp:328
    #2 0x72b3d08de413 in wobbly_transformer_node_t::update_model() ../plugins/wobbly/wobbly.cpp:676
    #3 0x72b3d08de413 in wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}::operator()() const ../plugins/wobbly/wobbly.cpp:858
    #4 0x72b3d08de413 in void std::__invoke_impl<void, wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}&>(std::__invoke_other, wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}&) /usr/include/c++/13.2.1/bits/invoke.h:61
    #5 0x72b3d08de413 in std::enable_if<is_invocable_r_v<void, wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}&>, void>::type std::__invoke_r<void, wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}&>(wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}&) /usr/include/c++/13.2.1/bits/invoke.h:111
    #6 0x72b3d08de413 in std::_Function_handler<void (), wobbly_render_instance_t::wobbly_render_instance_t(wobbly_transformer_node_t*, std::function<void (wf::region_t const&)>, wf::output_t*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) /usr/include/c++/13.2.1/bits/std_function.h:290
    #7 0x60f6b8614684 in std::function<void (wf::signal::connection_base_t*&)>::operator()(wf::signal::connection_base_t*&) const /usr/include/c++/13.2.1/bits/std_function.h:591
    #8 0x60f6b8614684 in wf::safe_list_t<std::function<void ()>*>::for_each(std::function<void (std::function<void ()>*&)>) ../src/api/wayfire/nonstd/safe-list.hpp:78
    #9 0x60f6b8614684 in wf::effect_hook_manager_t::run_effects(wf::output_effect_type_t) ../src/output/render-manager.cpp:491
    #10 0x60f6b8620875 in wf::render_manager::impl::paint() ../src/output/render-manager.cpp:1111
    #11 0x60f6b8629e7e in wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}::operator()(void*) const ../src/output/render-manager.cpp:959
    #12 0x60f6b8629e7e in void std::__invoke_impl<void, wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}&, void*>(std::__invoke_other, wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}&, void*&&) /usr/include/c++/13.2.1/bits/invoke.h:61
    #13 0x60f6b8629e7e in std::enable_if<is_invocable_r_v<void, wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}&, void*>, void>::type std::__invoke_r<void, wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}&, void*>(wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}&, void*&&) /usr/include/c++/13.2.1/bits/invoke.h:111
    #14 0x60f6b8629e7e in std::_Function_handler<void (void*), wf::render_manager::impl::impl(wf::output_t*)::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&) /usr/include/c++/13.2.1/bits/std_function.h:290
    #15 0x60f6b83552d9 in std::function<void (void*)>::operator()(void*) const /usr/include/c++/13.2.1/bits/std_function.h:591
    #16 0x60f6b83552d9 in wf::wl_listener_wrapper::emit(void*) ../src/wl-listener-wrapper.tpp:57
    #17 0x60f6b83552d9 in handle_wrapped_listener ../src/wl-listener-wrapper.tpp:10
    #18 0x72b3e49db01d in wl_signal_emit_mutable (/usr/lib/libwayland-server.so.0+0xa01d) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #19 0x72b3e4909218 in handle_page_flip ../wlroots-0.17.2/backend/drm/drm.c:1767
    #20 0x72b3e3f0d906 in drmHandleEvent (/usr/lib/libdrm.so.2+0xe906) (BuildId: 37b8c59fab0dabcaaf47293ff8e2b9fa19096a0a)
    #21 0x72b3e490744d in handle_drm_event ../wlroots-0.17.2/backend/drm/drm.c:1779
    #22 0x72b3e49dcae1 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbae1) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #23 0x72b3e49dd2d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #24 0x60f6b835015e in main ../src/main.cpp:447
    #25 0x72b3e3957ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #26 0x72b3e3957d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #27 0x60f6b8355034 in _start (/usr/bin/wayfire+0xfb034) (BuildId: 819dff10f6451299a5afcf73167ec906d56156ab)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE ../plugins/wobbly/wobbly.c:606 in wobbly_resize
==25004==ABORTING
(EE) failed to read Wayland events: Broken pipe
```

**Comment by killown** [comment]
reproduced this issues lot of times
