### ISSUE TITLE
[shutdown crash] output layout crashing wayfire [bindings related]

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2297]
crashed while testing wayfire with 200 views, crash happened after trying logout with alt+m which uses wayland-logout
<details>

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==44952==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x58796e3d7cf0 bp 0x7ffe88cd4840 sp 0x7ffe88cd3b20 T0)
==44952==The signal is caused by a READ memory access.
==44952==Hint: address points to the zero page.
    #0 0x58796e3d7cf0 in std::__uniq_ptr_impl<wf::bindings_repository_t::impl, std::default_delete<wf::bindings_repository_t::impl> >::_M_ptr() const /usr/include/c++/13.2.1/bits/unique_ptr.h:199
    #1 0x58796e3d7cf0 in std::unique_ptr<wf::bindings_repository_t::impl, std::default_delete<wf::bindings_repository_t::impl> >::get() const /usr/include/c++/13.2.1/bits/unique_ptr.h:470
    #2 0x58796e3d7cf0 in std::unique_ptr<wf::bindings_repository_t::impl, std::default_delete<wf::bindings_repository_t::impl> >::operator->() const /usr/include/c++/13.2.1/bits/unique_ptr.h:463
    #3 0x58796e3d7cf0 in wf::bindings_repository_t::rem_binding(void*) ../src/core/seat/bindings-repository.cpp:226
    #4 0x58796e565a2d in wf::output_impl_t::~output_impl_t() ../src/output/output.cpp:149
    #5 0x58796e3009a7 in wf::output_impl_t::~output_impl_t() ../src/output/output.cpp:157
    #6 0x58796e3009a7 in std::default_delete<wf::output_impl_t>::operator()(wf::output_impl_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #7 0x58796e3009a7 in std::unique_ptr<wf::output_impl_t, std::default_delete<wf::output_impl_t> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #8 0x58796e3009a7 in wf::output_layout_output_t::~output_layout_output_t() ../src/core/output-layout.cpp:253
    #9 0x58796e3009a7 in std::default_delete<wf::output_layout_output_t>::operator()(wf::output_layout_output_t*) const [clone .part.0] [clone .lto_priv.0] /usr/include/c++/13.2.1/bits/unique_ptr.h:99
    #10 0x58796e301f44 in std::default_delete<wf::output_layout_output_t>::operator()(wf::output_layout_output_t*) const /usr/include/c++/13.2.1/bits/unique_ptr.h:93
    #11 0x58796e301f44 in std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> >::~unique_ptr() /usr/include/c++/13.2.1/bits/unique_ptr.h:404
    #12 0x58796e301f44 in std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >::~pair() /usr/include/c++/13.2.1/bits/stl_pair.h:187
    #13 0x58796e301f44 in void std::__new_allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::destroy<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >(std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >*) /usr/include/c++/13.2.1/bits/new_allocator.h:194
    #14 0x58796e301f44 in void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > > >::destroy<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >(std::allocator<std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >&, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >*) /usr/include/c++/13.2.1/bits/alloc_traits.h:557
    #15 0x58796e301f44 in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_destroy_node(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:625
    #16 0x58796e301f44 in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_drop_node(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:633
    #17 0x58796e301f44 in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::_M_erase(std::_Rb_tree_node<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >*) /usr/include/c++/13.2.1/bits/stl_tree.h:1938
    #18 0x58796e301f44 in std::_Rb_tree<wlr_output*, std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > >, std::_Select1st<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::clear() /usr/include/c++/13.2.1/bits/stl_tree.h:1255
    #19 0x58796e301f44 in std::map<wlr_output*, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> >, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, std::unique_ptr<wf::output_layout_output_t, std::default_delete<wf::output_layout_output_t> > > > >::clear() /usr/include/c++/13.2.1/bits/stl_map.h:1184
    #20 0x58796e301f44 in wf::output_layout_t::impl::fini() ../src/core/output-layout.cpp:1024
    #21 0x58796e301f44 in wf::priv_output_layout_fini(wf::output_layout_t*) ../src/core/output-layout.cpp:1792
    #22 0x58796e3846e6 in wf::compositor_core_impl_t::fini() ../src/core/core.cpp:273
    #23 0x58796e3853c1 in wf::compositor_core_impl_t::deallocate_core() ../src/core/core.cpp:586
    #24 0x58796e2ad163 in main ../src/main.cpp:448
    #25 0x741c2f757ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #26 0x741c2f757d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #27 0x58796e2b2034 in _start (/usr/bin/wayfire+0xfb034) (BuildId: 819dff10f6451299a5afcf73167ec906d56156ab)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/13.2.1/bits/unique_ptr.h:199 in std::__uniq_ptr_impl<wf::bindings_repository_t::impl, std::default_delete<wf::bindings_repository_t::impl> >::_M_ptr() const
==44952==ABORTING
```

**Comment by killown** [comment]
use this code for the stress test

```
# Note: You need to update waypy again to use this
# because it now has 'killall -9 terminal'. 
# Every new iteration, it should restart with newly defined views
# plugins =
#     stipc autostart command foreign-toplevel filters gtk-shell ipc ipc-rules resize
#     shortcuts-inhibit window-rules workspace-names xdg-activation wayfire-shell
#     grid switcher force-fullscreen fast-switcher place wobbly alpha expo wsets
#     oswitch idle preserve-output obs vswitch wm-actions follow-focus vswipe
#     focus-steal-prevent focus-change move view-shot session-lock animate cube
#     invert mag zoom fisheye water wrot winzoom simple-tile scale


from wayfire.ipc import sock
from random import randint

while True:
    number_of_views = randint(1, 20)
    number_of_executions = randint(100, 1000)
    random_time_to_wait = randint(1, 40000)
    sock.test_wayfire(number_of_views, number_of_executions, random_time_to_wait)

```
