### ISSUE TITLE
wayland issue crashing wayfire

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2301]
new level of fuzzy tests
<details>

```
II 01-04-24 22:05:01.816 - [src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: ᴚ򱌳䎢򲆲򓱣񽄦�𯰖𾕣򆟓 app-id: ipython
II 01-04-24 22:05:01.819 - [wayland] file descriptor expected, object (1224), message add(huuuuu)
II 01-04-24 22:05:01.820 - [wayland] error in client communication (pid 57153)
II 01-04-24 22:05:01.820 - [xwayland/server.c:218] Restarting Xwayland
XWAYLAND: wl_display@1: error 1: invalid arguments for zwp_linux_buffer_params_v1@1224.add
(EE) failed to dispatch Wayland events: Invalid argument
II 01-04-24 22:05:01.855 - [xwayland/server.c:108] Starting Xwayland on :1
EE 01-04-24 22:05:01.882 - [types/wlr_compositor.c:938] surface output destroyed 0x5070016b9e20 bind=0x5070016b9e40
EE 01-04-24 22:05:01.892 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be59c0 bind=0x507000be59e0
EE 01-04-24 22:05:01.902 - [types/wlr_compositor.c:938] surface output destroyed 0x507000ba6950 bind=0x507000ba6970
(EE) could not connect to wayland server
EE 01-04-24 22:05:01.918 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be5db0 bind=0x507000be5dd0
EE 01-04-24 22:05:01.925 - [types/wlr_compositor.c:938] surface output destroyed 0x50700167fce0 bind=0x50700167fd00
EE 01-04-24 22:05:01.932 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc600 bind=0x507001efc620
EE 01-04-24 22:05:01.940 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be35e0 bind=0x507000be3600
EE 01-04-24 22:05:01.944 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb3a0 bind=0x507001efb3c0
EE 01-04-24 22:05:01.961 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc910 bind=0x507001efc930
EE 01-04-24 22:05:01.961 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d3870 bind=0x5070013d3890
EE 01-04-24 22:05:01.961 - [types/wlr_compositor.c:938] surface output destroyed 0x5070001f5700 bind=0x5070001f5720
EE 01-04-24 22:05:02.015 - [types/wlr_compositor.c:938] surface output destroyed 0x5070000aa6a0 bind=0x5070000aa6c0
EE 01-04-24 22:05:02.018 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d1f80 bind=0x5070013d1fa0
EE 01-04-24 22:05:02.022 - [types/wlr_compositor.c:938] surface output destroyed 0x50700028d860 bind=0x50700028d880
EE 01-04-24 22:05:02.024 - [types/wlr_compositor.c:938] surface output destroyed 0x5070015cb3a0 bind=0x5070015cb3c0
EE 01-04-24 22:05:02.026 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efa610 bind=0x507001efa630
EE 01-04-24 22:05:02.029 - [types/wlr_compositor.c:938] surface output destroyed 0x507000214f70 bind=0x507000214f90
EE 01-04-24 22:05:02.034 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d3b10 bind=0x5070013d3b30
EE 01-04-24 22:05:02.034 - [types/wlr_compositor.c:938] surface output destroyed 0x507000ba81d0 bind=0x507000ba81f0
EE 01-04-24 22:05:02.036 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc520 bind=0x507001efc540
EE 01-04-24 22:05:02.038 - [types/wlr_compositor.c:938] surface output destroyed 0x507000284f70 bind=0x507000284f90
EE 01-04-24 22:05:02.042 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be5b80 bind=0x507000be5ba0
EE 01-04-24 22:05:02.045 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bd4e00 bind=0x507000bd4e20
EE 01-04-24 22:05:02.047 - [types/wlr_compositor.c:938] surface output destroyed 0x507000ba73d0 bind=0x507000ba73f0
EE 01-04-24 22:05:02.047 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be9620 bind=0x507000be9640
EE 01-04-24 22:05:02.049 - [types/wlr_compositor.c:938] surface output destroyed 0x5070016c4150 bind=0x5070016c4170
EE 01-04-24 22:05:02.049 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be9000 bind=0x507000be9020
EE 01-04-24 22:05:02.049 - [types/wlr_compositor.c:938] surface output destroyed 0x507000292b10 bind=0x507000292b30
EE 01-04-24 22:05:02.051 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc590 bind=0x507001efc5b0
EE 01-04-24 22:05:02.051 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bcef10 bind=0x507000bcef30
EE 01-04-24 22:05:02.051 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d1960 bind=0x5070013d1980
EE 01-04-24 22:05:02.052 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bcac90 bind=0x507000bcacb0
EE 01-04-24 22:05:02.053 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efaf40 bind=0x507001efaf60
EE 01-04-24 22:05:02.054 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be8e40 bind=0x507000be8e60
EE 01-04-24 22:05:02.057 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb2c0 bind=0x507001efb2e0
EE 01-04-24 22:05:02.059 - [types/wlr_compositor.c:938] surface output destroyed 0x507000201630 bind=0x507000201650
EE 01-04-24 22:05:02.063 - [types/wlr_compositor.c:938] surface output destroyed 0x50700028f690 bind=0x50700028f6b0
EE 01-04-24 22:05:02.065 - [types/wlr_compositor.c:938] surface output destroyed 0x507000293910 bind=0x507000293930
EE 01-04-24 22:05:02.066 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be8d60 bind=0x507000be8d80
EE 01-04-24 22:05:02.066 - [types/wlr_compositor.c:938] surface output destroyed 0x5070002000c0 bind=0x5070002000e0
EE 01-04-24 22:05:02.071 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d3560 bind=0x5070013d3580
EE 01-04-24 22:05:02.073 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d35d0 bind=0x5070013d35f0
EE 01-04-24 22:05:02.073 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bd8c90 bind=0x507000bd8cb0
EE 01-04-24 22:05:02.076 - [types/wlr_compositor.c:938] surface output destroyed 0x507000b49490 bind=0x507000b494b0
EE 01-04-24 22:05:02.078 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be9150 bind=0x507000be9170
EE 01-04-24 22:05:02.079 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bd1600 bind=0x507000bd1620
EE 01-04-24 22:05:02.079 - [types/wlr_compositor.c:938] surface output destroyed 0x507000baaee0 bind=0x507000baaf00
EE 01-04-24 22:05:02.080 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bd7f00 bind=0x507000bd7f20
EE 01-04-24 22:05:02.081 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efcad0 bind=0x507001efcaf0
EE 01-04-24 22:05:02.083 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bcad00 bind=0x507000bcad20
EE 01-04-24 22:05:02.083 - [types/wlr_compositor.c:938] surface output destroyed 0x5070015cb250 bind=0x5070015cb270
EE 01-04-24 22:05:02.083 - [types/wlr_compositor.c:938] surface output destroyed 0x507000be92a0 bind=0x507000be92c0
EE 01-04-24 22:05:02.083 - [types/wlr_compositor.c:938] surface output destroyed 0x507000b4d6a0 bind=0x507000b4d6c0
EE 01-04-24 22:05:02.083 - [types/wlr_compositor.c:938] surface output destroyed 0x50700028fcb0 bind=0x50700028fcd0
EE 01-04-24 22:05:02.085 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb090 bind=0x507001efb0b0
EE 01-04-24 22:05:02.085 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc4b0 bind=0x507001efc4d0
EE 01-04-24 22:05:02.086 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb250 bind=0x507001efb270
EE 01-04-24 22:05:02.087 - [types/wlr_compositor.c:938] surface output destroyed 0x507000bc6e70 bind=0x507000bc6e90
EE 01-04-24 22:05:02.087 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efca60 bind=0x507001efca80
EE 01-04-24 22:05:02.088 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb330 bind=0x507001efb350
EE 01-04-24 22:05:02.090 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efd080 bind=0x507001efd0a0
EE 01-04-24 22:05:02.091 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efd160 bind=0x507001efd180
EE 01-04-24 22:05:02.092 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efa840 bind=0x507001efa860
EE 01-04-24 22:05:02.094 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efcec0 bind=0x507001efcee0
EE 01-04-24 22:05:02.095 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efd0f0 bind=0x507001efd110
EE 01-04-24 22:05:02.096 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efcb40 bind=0x507001efcb60
EE 01-04-24 22:05:02.098 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc670 bind=0x507001efc690
EE 01-04-24 22:05:02.099 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc440 bind=0x507001efc460
EE 01-04-24 22:05:02.100 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc7c0 bind=0x507001efc7e0
EE 01-04-24 22:05:02.101 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc3d0 bind=0x507001efc3f0
EE 01-04-24 22:05:02.102 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efad80 bind=0x507001efada0
EE 01-04-24 22:05:02.103 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efa8b0 bind=0x507001efa8d0
EE 01-04-24 22:05:02.104 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efa680 bind=0x507001efa6a0
EE 01-04-24 22:05:02.105 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efb1e0 bind=0x507001efb200
EE 01-04-24 22:05:02.106 - [types/wlr_compositor.c:938] surface output destroyed 0x5070013d0a10 bind=0x5070013d0a30
EE 01-04-24 22:05:02.106 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc750 bind=0x507001efc770
EE 01-04-24 22:05:02.107 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc830 bind=0x507001efc850
EE 01-04-24 22:05:02.108 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc8a0 bind=0x507001efc8c0
EE 01-04-24 22:05:02.109 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc9f0 bind=0x507001efca10
EE 01-04-24 22:05:02.109 - [types/wlr_compositor.c:938] surface output destroyed 0x507001efc980 bind=0x507001efc9a0
EE 01-04-24 22:05:02.198 - [xwayland/server.c:270] Xwayland startup failed, not setting up xwm
AddressSanitizer:DEADLYSIGNAL
=================================================================
==57153==ERROR: AddressSanitizer: SEGV on unknown address 0x000000008061 (pc 0x72429aaec3e5 bp 0x511000c73700 sp 0x7ffeae0678a0 T0)
==57153==The signal is caused by a READ memory access.
    #0 0x72429aaec3e5  (/usr/lib/libwayland-server.so.0+0x83e5) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #1 0x72429aaf0099 in wl_client_destroy (/usr/lib/libwayland-server.so.0+0xc099) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #2 0x72429a388622 in server_finish_process ../wlroots-0.17.2/xwayland/server.c:154
    #3 0x72429a38ba42 in server_finish_process ../wlroots-0.17.2/xwayland/server.c:141
    #4 0x72429a38ba42 in xserver_handle_ready ../wlroots-0.17.2/xwayland/server.c:292
    #5 0x72429aaefae1 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbae1) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #6 0x72429aaf02d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #7 0x6062fe4ae5ae in main ../src/main.cpp:447
    #8 0x724299a43ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #9 0x724299a43d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #10 0x6062fe4b3484 in _start (/usr/bin/wayfire+0xfc484) (BuildId: 369f99b793d22291fbbfdf2d952acc4f99f53b29)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libwayland-server.so.0+0x83e5) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19) 
==57153==ABORTING
```

```

sock.test_random_change_view_state(466)
sock.test_change_view_state(466)
sock.test_change_view_state(466)
sock.test_random_list_info(466)
sock.set_workspace({'x': 0, 'y': 0}, 466, 3)
sock.test_random_set_view_position(466)
sock.set_focus(466)
sock.test_list_info(466)
sock.test_random_set_view_position(466)
sock.set_focus(466)
sock.test_random_change_view_state(466)
sock.click_and_drag('S-BTN_LEFT', 3923, 957, 3849, 1613, True)
sock.set_workspace({'x': 0, 'y': 0}, 466, 3)
sock.set_workspace({'x': 0, 'y': 0}, 466, 3)
sock.go_next_workspace_with_views()
sock.go_next_workspace_with_views()
sock.set_focus(466)
sock.configure_view(466, 1959, 532, 3353, 1050)
sock.test_random_list_info(466)
sock.test_random_set_view_position(466)
sock.click_and_drag('S-BTN_LEFT', 3923, 957, 3849, 1613, True)
sock.set_focus(466)
sock.set_workspace({'x': 0, 'y': 0}, 466, 3)
sock.test_random_change_view_state(466)
sock.test_plugins()
sock.test_plugins()
sock.test_change_view_state(466)
sock.go_next_workspace_with_views()
```

**Comment by ammen99** [comment]
Seems like a Xwayland/wlroots crash, can't fix it in Wayfire.
