### ISSUE TITLE
new wayland issue crashing wayfire

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2302]
edit the title if you identify what is this, ty

```
E 01-04-24 22:10:40.429 - [types/wlr_compositor.c:938] surface output destroyed 0x507003029a90 bind=0x507003029ab0
DD 01-04-24 22:10:40.440 - [src/core/idle.cpp:27] destroying idle inhibitor 0x51a00008d318 previous count: 1
DD 01-04-24 22:10:40.440 - [src/output/promotion-manager.hpp:123] restore panels
DD 01-04-24 22:10:40.442 - [src/output/output.cpp:318] output DP-1: deactivate plugin vswitch
EE 01-04-24 22:10:40.465 - [types/wlr_compositor.c:982] surface output bind start 0x5070024aab00 0x5070024aaae0
DD 01-04-24 22:10:40.467 - [plugins/ipc/ipc.cpp:122] Removing IPC client 0x5080004c9320
EE 01-04-24 22:10:40.499 - [types/wlr_compositor.c:938] surface output destroyed 0x5070001a12a0 bind=0x5070001a12c0
EE 01-04-24 22:10:40.501 - [xwayland/server.c:270] Xwayland startup failed, not setting up xwm
AddressSanitizer:DEADLYSIGNAL
=================================================================
==60832==ERROR: AddressSanitizer: SEGV on unknown address 0x000000008071 (pc 0x783841d0a3e5 bp 0x511001972000 sp 0x7fff9bf530d0 T0)
==60832==The signal is caused by a READ memory access.
    #0 0x783841d0a3e5  (/usr/lib/libwayland-server.so.0+0x83e5) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #1 0x783841d0e099 in wl_client_destroy (/usr/lib/libwayland-server.so.0+0xc099) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #2 0x783841588622 in server_finish_process ../wlroots-0.17.2/xwayland/server.c:154
    #3 0x78384158ba42 in server_finish_process ../wlroots-0.17.2/xwayland/server.c:141
    #4 0x78384158ba42 in xserver_handle_ready ../wlroots-0.17.2/xwayland/server.c:292
    #5 0x783841d0dae1 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xbae1) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #6 0x783841d0e2d6 in wl_display_run (/usr/lib/libwayland-server.so.0+0xc2d6) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19)
    #7 0x5ddccc7bb5ae in main ../src/main.cpp:447
    #8 0x783840c43ccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #9 0x783840c43d89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #10 0x5ddccc7c0484 in _start (/usr/bin/wayfire+0xfc484) (BuildId: 369f99b793d22291fbbfdf2d952acc4f99f53b29)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libwayland-server.so.0+0x83e5) (BuildId: d943a6a6069d1b5293dad7c842d26ce407ebdd19) 
==60832==ABORTING
```

**Comment by ammen99** [comment]
Duplicate of #2301
