### ISSUE TITLE
wf-panel crashes after playing a song on spotify

### ISSUE THREAD

**Issue by dxcy47** [WayfireWM/wayfire#2536]
**Describe the bug**
whenever i open spotify and play a song, wf-panel crashes

**To Reproduce**
1. open spotify
2. play a song
3. wf-panel crashes
(note: it only crashes after playing a song. if i keep spotify open without playing anything it still works fine)

**Expected behavior**
expected wf-panel to work as normal without crashing after opening spotify

**Screenshots or stacktrace**

II 13-12-24 16:56:27.275 - [subprojects/wf-config/src/file.cpp:579] Reading XML configuration options from directory /opt/wayfire/share/wayfire/metadata/wf-shell
II 13-12-24 16:56:27.275 - [subprojects/wf-config/src/file.cpp:529] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/background.xml
II 13-12-24 16:56:27.275 - [subprojects/wf-config/src/file.cpp:529] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/dock.xml
II 13-12-24 16:56:27.275 - [subprojects/wf-config/src/file.cpp:529] Reading XML configuration options from file /opt/wayfire/share/wayfire/metadata/wf-shell/panel.xml
EE 13-12-24 16:56:27.276 - [subprojects/wf-config/src/file.cpp:341] Error in file /home/decoy/.config/wf-shell.ini:100, invalid option value!
EE 13-12-24 16:56:27.276 - [subprojects/wf-config/src/file.cpp:341] Error in file /home/decoy/.config/wf-shell.ini:100, invalid option value!
Error loading file: /usr/share/icons/gnome/48x48/categories/preferences-system.png
target button 508
set width 192

** (wf-panel:2594): ERROR **: 16:56:36.190:
unhandled exception (type std::exception) in signal handler:
what: map::at

fish: Job 1, 'wf-panel' terminated by signal SIGTRAP (Trace or breakpoint trap)

-----
this is the whole log from starting wf-panel to it crashing

**Wayfire version**
wayfire-git 0.9.0 installed with wf-install

**Comment by NamorNiradnug** [comment]
Hi! Could you please run `wf-panel` under `gdb` and report the stacktrace of the thrown exception? I am pretty sure this is a problem about nofifications widget.

Also this issue should be transferred to wf-shell repo.

**Comment by bell07** [comment]
Same issue on my site.
Recompiled the wayfire and wf-panel (both in version 0.9.0) with CFLAGS="-ggdb3" and splitdebug (Gentoo way):


```
$ gdb wf-panel 
GNU gdb (Gentoo 15.2 vanilla) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from wf-panel...
Reading symbols from /usr/lib/debug//usr/bin/wf-panel.debug...
(gdb) run
Starting program: /usr/bin/wf-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff2bb76c0 (LWP 6939)]
[New Thread 0x7ffff23b66c0 (LWP 6940)]
[New Thread 0x7ffff1bb56c0 (LWP 6941)]
[New Thread 0x7ffff138d6c0 (LWP 6942)]
[New Thread 0x7ffff0b126c0 (LWP 6943)]
II 09-01-25 08:59:27.591 - [wf-config-0.9.0/src/file.cpp:579] Reading XML configuration options from directory /usr/share/wayfire/metadata/wf-shell
II 09-01-25 08:59:27.591 - [wf-config-0.9.0/src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/dock.xml
II 09-01-25 08:59:27.591 - [wf-config-0.9.0/src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/panel.xml
II 09-01-25 08:59:27.591 - [wf-config-0.9.0/src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/background.xml
[New Thread 0x7fffdbfff6c0 (LWP 6944)]
[New Thread 0x7fffda7ff6c0 (LWP 6945)]
Error loading file: notifications
Error loading file: notifications
target button 1973
set width 256
[Thread 0x7fffda7ff6c0 (LWP 6945) exited]

(wf-panel:6936): Gtk-WARNING **: 08:59:34.611: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
[Detaching after fork from child process 6954]
[New Thread 0x7fffda7ff6c0 (LWP 6956)]
Neither gnome-integration-spotify nor spotify-tray are installed.
Launching spotify without systray integration.
[Thread 0x7fffda7ff6c0 (LWP 6956) exited]

** (wf-panel:6936): ERROR **: 08:59:43.714: 
unhandled exception (type std::exception) in signal handler:
what: map::at

Thread 1 "wf-panel" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff68a88e7 in g_log_structured_array () from /usr/lib64/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff68a88e7 in g_log_structured_array () at /usr/lib64/libglib-2.0.so.0
#1  0x00007ffff68a8d47 in g_log_default_handler () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff68a9071 in g_logv () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff68a93db in g_log () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff6b7839a in ??? () at /usr/lib64/libglibmm-2.4.so.1
#5  0x00007ffff74e5ede in ??? () at /usr/lib64/libgiomm-2.4.so.1
#6  0x00007ffff7725aca in ??? () at /usr/lib64/libgio-2.0.so.0
#7  0x00007ffff689d267 in ??? () at /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff68a05f7 in ??? () at /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff68a0c20 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff76f8ff5 in g_application_run () at /usr/lib64/libgio-2.0.so.0
#11 0x000055555559810d in main ()
(gdb) exit
A debugging session is active.

	Inferior 1 [process 6936] will be killed.

Quit anyway? (y or n) y

```
