### ISSUE TITLE
Crash on exit if window is wobblying

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#718]
Stack trace:

<details>
```
==663359==The signal is caused by a READ memory access.
==663359==Hint: address points to the zero page.
    #0 0x68625a in std::__uniq_ptr_impl<wf::render_manager, std::default_delete<wf::render_manager> >::_M_ptr() const /usr/include/c++/10/bits/unique_ptr.h:173
    #1 0x677f35 in std::unique_ptr<wf::render_manager, std::default_delete<wf::render_manager> >::get() const /usr/include/c++/10/bits/unique_ptr.h:422
    #2 0x669e90 in std::unique_ptr<wf::render_manager, std::default_delete<wf::render_manager> >::operator->() const /usr/include/c++/10/bits/unique_ptr.h:416
    #3 0x7f43c21482db in wf_wobbly::~wf_wobbly() ../plugins/wobbly/wobbly.cpp:775
    #4 0x7f43c21497bf in wf_wobbly::~wf_wobbly() ../plugins/wobbly/wobbly.cpp:782
    #5 0x8ff60d in std::default_delete<wf::view_transformer_t>::operator()(wf::view_transformer_t*) const /usr/include/c++/10/bits/unique_ptr.h:85
    #6 0x8f9a0b in std::unique_ptr<wf::view_transformer_t, std::default_delete<wf::view_transformer_t> >::~unique_ptr() /usr/include/c++/10/bits/unique_ptr.h:361
    #7 0x8e66c2 in wf::view_transform_block_t::~view_transform_block_t() ../src/view/view.cpp:1053
    #8 0x9102d0 in void __gnu_cxx::new_allocator<wf::view_transform_block_t>::destroy<wf::view_transform_block_t>(wf::view_transform_block_t*) /usr/include/c++/10/ext/new_allocator.h:156
    #9 0x910268 in void std::allocator_traits<std::allocator<wf::view_transform_block_t> >::destroy<wf::view_transform_block_t>(std::allocator<wf::view_transform_block_t>&, wf::view_transform_block_t*) /usr/include/c++/10/bits/alloc_traits.h:531
    #10 0x90fcf8 in std::_Sp_counted_ptr_inplace<wf::view_transform_block_t, std::allocator<wf::view_transform_block_t>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10/bits/shared_ptr_base.h:560
    #11 0x67587c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10/bits/shared_ptr_base.h:158
    #12 0x6684fe in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10/bits/shared_ptr_base.h:733
    #13 0x8f63a4 in std::__shared_ptr<wf::view_transform_block_t, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (/usr/bin/wayfire+0x8f63a4)
    #14 0x8f6407 in std::shared_ptr<wf::view_transform_block_t>::~shared_ptr() (/usr/bin/wayfire+0x8f6407)
    #15 0x905fef in std::default_delete<std::shared_ptr<wf::view_transform_block_t> >::operator()(std::shared_ptr<wf::view_transform_block_t>*) const /usr/include/c++/10/bits/unique_ptr.h:85
    #16 0x90051f in std::unique_ptr<std::shared_ptr<wf::view_transform_block_t>, std::default_delete<std::shared_ptr<wf::view_transform_block_t> > >::~unique_ptr() /usr/include/c++/10/bits/unique_ptr.h:361
    #17 0x8fabc4 in wf::safe_list_t<std::shared_ptr<wf::view_transform_block_t> >::remove_if(std::function<bool (std::shared_ptr<wf::view_transform_block_t> const&)>) ../src/api/wayfire/nonstd/safe-list.hpp:244
    #18 0x8db85e in wf::view_interface_t::pop_transformer(nonstd::observer_ptr<wf::view_transformer_t>) ../src/view/view.cpp:784
    #19 0x8dc0e0 in wf::view_interface_t::pop_transformer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../src/view/view.cpp:801
    #20 0x7f43c2147ccd in wf_wobbly::destroy_self() ../plugins/wobbly/wobbly.cpp:768
    #21 0x7f43c213de64 in wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}::operator()(wf::signal_data_t) const ../plugins/wobbly/wobbly.cpp:513
    #22 0x7f43c216976d in void std::__invoke_impl<void, wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}&, wf::signal_data_t>(std::__invoke_other, wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}&, wf::signal_data_t&&) /usr/include/c++/10/bits/invoke.h:60
    #23 0x7f43c216359f in std::enable_if<is_invocable_r_v<void, wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}&, wf::signal_data_t>, wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}&>::type std::__invoke_r<void, wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}&, wf::signal_data_t>(std::enable_if&&, (void&&)...) /usr/include/c++/10/bits/invoke.h:110
    #24 0x7f43c215a5fb in std::_Function_handler<void (wf::signal_data_t*), wf_wobbly::view_output_changed::{lambda(wf::signal_data_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal_data_t*&&) /usr/include/c++/10/bits/std_function.h:291
    #25 0x6c7ab6 in std::function<void (wf::signal_data_t*)>::operator()(wf::signal_data_t*) const /usr/include/c++/10/bits/std_function.h:622
    #26 0x6c020a in operator()<std::function<void(wf::signal_data_t*)>*> ../src/core/object.cpp:136
    #27 0x6c4e31 in __invoke_impl<void, wf::signal_provider_t::emit_signal(std::string, wf::signal_data_t*)::<lambda(auto:3)>&, std::function<void(wf::signal_data_t*)>*&> /usr/include/c++/10/bits/invoke.h:60
    #28 0x6c41d9 in __invoke_r<void, wf::signal_provider_t::emit_signal(std::string, wf::signal_data_t*)::<lambda(auto:3)>&, std::function<void(wf::signal_data_t*)>*&> /usr/include/c++/10/bits/invoke.h:110
    #29 0x6c329e in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #30 0x6d2025 in std::function<void (std::function<void (wf::signal_data_t*)>*&)>::operator()(std::function<void (wf::signal_data_t*)>*&) const /usr/include/c++/10/bits/std_function.h:622
    #31 0x6ca8e6 in wf::safe_list_t<std::function<void (wf::signal_data_t*)>*>::for_each(std::function<void (std::function<void (wf::signal_data_t*)>*&)>) const (/usr/bin/wayfire+0x6ca8e6)
    #32 0x6c053c in wf::signal_provider_t::emit_signal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wf::signal_data_t*) ../src/core/object.cpp:134
    #33 0x8c1207 in wf::view_interface_t::set_output(wf::output_t*) ../src/view/view.cpp:209
    #34 0x91e0e1 in wf::wlr_view_t::set_output(wf::output_t*) ../src/view/view-impl.cpp:287
    #35 0x63ce22 in wf::transfer_views(wf::output_t*, wf::output_t*) ../src/core/output-layout.cpp:251
    #36 0x64b2c9 in wf::output_layout_output_t::destroy_wayfire_output(bool) ../src/core/output-layout.cpp:587
    #37 0x654081 in wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}::operator()(void*) const (/usr/bin/wayfire+0x654081)
    #38 0x69efbf in void std::__invoke_impl<void, wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}&, wf::signal_data_t*>(std::__invoke_other, wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}&, wf::signal_data_t*&&) (/usr/bin/wayfire+0x69efbf)
    #39 0x696a94 in std::enable_if<is_invocable_r_v<void, wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}&, wf::signal_data_t*>, std::enable_if>::type std::__invoke_r<void, wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}&, wf::signal_data_t*>(void&&, (wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}&)...) (/usr/bin/wayfire+0x696a94)
    #40 0x689090 in std::_Function_handler<void (wf::signal_data_t*), wf::output_layout_t::impl::impl(wlr_backend*)::{lambda(void*)#3}>::_M_invoke(std::_Any_data const&, wf::signal_data_t*&&) (/usr/bin/wayfire+0x689090)
    #41 0x6c7ab6 in std::function<void (wf::signal_data_t*)>::operator()(wf::signal_data_t*) const /usr/include/c++/10/bits/std_function.h:622
    #42 0x6c020a in operator()<std::function<void(wf::signal_data_t*)>*> ../src/core/object.cpp:136
    #43 0x6c4e31 in __invoke_impl<void, wf::signal_provider_t::emit_signal(std::string, wf::signal_data_t*)::<lambda(auto:3)>&, std::function<void(wf::signal_data_t*)>*&> /usr/include/c++/10/bits/invoke.h:60
    #44 0x6c41d9 in __invoke_r<void, wf::signal_provider_t::emit_signal(std::string, wf::signal_data_t*)::<lambda(auto:3)>&, std::function<void(wf::signal_data_t*)>*&> /usr/include/c++/10/bits/invoke.h:110
    #45 0x6c329e in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #46 0x6d2025 in std::function<void (std::function<void (wf::signal_data_t*)>*&)>::operator()(std::function<void (wf::signal_data_t*)>*&) const /usr/include/c++/10/bits/std_function.h:622
    #47 0x6ca8e6 in wf::safe_list_t<std::function<void (wf::signal_data_t*)>*>::for_each(std::function<void (std::function<void (wf::signal_data_t*)>*&)>) const (/usr/bin/wayfire+0x6ca8e6)
    #48 0x6c053c in wf::signal_provider_t::emit_signal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wf::signal_data_t*) ../src/core/object.cpp:134
    #49 0x72f70e in wf::compositor_core_impl_t::shutdown() ../src/core/core.cpp:726
    #50 0x770b58 in idle_shutdown ../src/core/wm.cpp:25
    #51 0x7f43f5250b02 in wl_event_loop_dispatch_idle (/lib64/libwayland-server.so.0+0xbb02)
    #52 0x7f43f5250c3c in wl_event_loop_dispatch (/lib64/libwayland-server.so.0+0xbc3c)
    #53 0x7f43f524e774 in wl_display_run (/lib64/libwayland-server.so.0+0x9774)
    #54 0x6144f8 in main ../src/main.cpp:393
    #55 0x7f43f3fcb041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #56 0x6089cd in _start (/usr/bin/wayfire+0x6089cd)
```

**Comment by ammen99** [comment]
Fixed in #759
